/*==========================================================================*\
 |  _EmailAlertForStudent.java
 |*-------------------------------------------------------------------------*|
 |  Created by eogenerator
 |  DO NOT EDIT.  Make changes to EmailAlertForStudent.java instead.
 |*-------------------------------------------------------------------------*|
 |  Copyright (C) 2006-2012 Virginia Tech
 |
 |  This file is part of Web-CAT.
 |
 |  Web-CAT is free software; you can redistribute it and/or modify
 |  it under the terms of the GNU Affero General Public License as published
 |  by the Free Software Foundation; either version 3 of the License, or
 |  (at your option) any later version.
 |
 |  Web-CAT is distributed in the hope that it will be useful,
 |  but WITHOUT ANY WARRANTY; without even the implied warranty of
 |  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 |  GNU General Public License for more details.
 |
 |  You should have received a copy of the GNU Affero General Public License
 |  along with Web-CAT; if not, see <http://www.gnu.org/licenses/>.
\*==========================================================================*/

package org.webcat.schedulesheets;

import com.webobjects.eoaccess.*;
import com.webobjects.eocontrol.*;
import com.webobjects.foundation.*;
import er.extensions.eof.ERXEOControlUtilities;
import er.extensions.eof.ERXKey;
import org.apache.log4j.Logger;
import org.webcat.core.EOBasedKeyGenerator;
import org.webcat.woextensions.WCFetchSpecification;

// -------------------------------------------------------------------------
/**
 * An automatically generated EOGenericRecord subclass.  DO NOT EDIT.
 * To change, use EOModeler, or make additions in
 * EmailAlertForStudent.java.
 *
 * @author Generated by eogenerator
 * @version version suppressed to control auto-generation
 */
public abstract class _EmailAlertForStudent
    extends org.webcat.core.EOBase
{
    //~ Constructors ..........................................................

    // ----------------------------------------------------------
    /**
     * Creates a new _EmailAlertForStudent object.
     */
    public _EmailAlertForStudent()
    {
        super();
    }


    // ----------------------------------------------------------
    /**
     * A static factory method for creating a new
     * EmailAlertForStudent object given required
     * attributes and relationships.
     * @param editingContext The context in which the new object will be
     * inserted
     * @param sentValue
     * @param alertOfferingValue
     * @param userValue
     * @return The newly created object
     */
    public static EmailAlertForStudent create(
        EOEditingContext editingContext,
        boolean sentValue,
        org.webcat.schedulesheets.EmailAlertForAssignmentOffering alertOfferingValue,
        org.webcat.core.User userValue
        )
    {
        EmailAlertForStudent eoObject = (EmailAlertForStudent)
            EOUtilities.createAndInsertInstance(
                editingContext,
                _EmailAlertForStudent.ENTITY_NAME);
        eoObject.setSent(sentValue);
        eoObject.setAlertOfferingRelationship(alertOfferingValue);
        eoObject.setUserRelationship(userValue);
        return eoObject;
    }


    // ----------------------------------------------------------
    /**
     * Get a local instance of the given object in another editing context.
     * @param editingContext The target editing context
     * @param eo The object to import
     * @return An instance of the given object in the target editing context
     */
    public static EmailAlertForStudent localInstance(
        EOEditingContext editingContext, EmailAlertForStudent eo)
    {
        return (eo == null)
            ? null
            : (EmailAlertForStudent)EOUtilities.localInstanceOfObject(
                editingContext, eo);
    }


    // ----------------------------------------------------------
    /**
     * Look up an object by id number.  Assumes the editing
     * context is appropriately locked.
     * @param ec The editing context to use
     * @param id The id to look up
     * @return The object, or null if no such id exists
     */
    public static EmailAlertForStudent forId(
        EOEditingContext ec, int id)
    {
        EmailAlertForStudent obj = null;
        if (id > 0)
        {
            NSArray<EmailAlertForStudent> objects =
                objectsMatchingValues(ec, "id", new Integer(id));
            if (objects != null && objects.count() > 0)
            {
                obj = objects.objectAtIndex(0);
            }
        }
        return obj;
    }


    // ----------------------------------------------------------
    /**
     * Look up an object by id number.  Assumes the editing
     * context is appropriately locked.
     * @param ec The editing context to use
     * @param id The id to look up
     * @return The object, or null if no such id exists
     */
    public static EmailAlertForStudent forId(
        EOEditingContext ec, String id)
    {
        return forId(ec, er.extensions.foundation.ERXValueUtilities.intValue(id));
    }


    //~ Constants (for key names) .............................................

    // Attributes ---
    public static final String BYTE_CODING_RATING_KEY = "byteCodingRating";
    public static final ERXKey<Integer> byteCodingRating =
        new ERXKey<Integer>(BYTE_CODING_RATING_KEY);
    public static final String BYTE_CORRECTNESS_RATING_KEY = "byteCorrectnessRating";
    public static final ERXKey<Integer> byteCorrectnessRating =
        new ERXKey<Integer>(BYTE_CORRECTNESS_RATING_KEY);
    public static final String BYTE_STYLE_RATING_KEY = "byteStyleRating";
    public static final ERXKey<Integer> byteStyleRating =
        new ERXKey<Integer>(BYTE_STYLE_RATING_KEY);
    public static final String BYTE_TESTING_RATING_KEY = "byteTestingRating";
    public static final ERXKey<Integer> byteTestingRating =
        new ERXKey<Integer>(BYTE_TESTING_RATING_KEY);
    public static final String SENT_KEY = "sent";
    public static final ERXKey<Integer> sent =
        new ERXKey<Integer>(SENT_KEY);
    // To-one relationships ---
    public static final String ALERT_OFFERING_KEY = "alertOffering";
    public static final ERXKey<org.webcat.schedulesheets.EmailAlertForAssignmentOffering> alertOffering =
        new ERXKey<org.webcat.schedulesheets.EmailAlertForAssignmentOffering>(ALERT_OFFERING_KEY);
    public static final String SUBMISSION_KEY = "submission";
    public static final ERXKey<org.webcat.grader.Submission> submission =
        new ERXKey<org.webcat.grader.Submission>(SUBMISSION_KEY);
    public static final String USER_KEY = "user";
    public static final ERXKey<org.webcat.core.User> user =
        new ERXKey<org.webcat.core.User>(USER_KEY);
    // To-many relationships ---
    // Fetch specifications ---
    public static final String ENTITY_NAME = "EmailAlertForStudent";

    public transient final EOBasedKeyGenerator generateKey =
        new EOBasedKeyGenerator(this);


    //~ Methods ...............................................................

    // ----------------------------------------------------------
    /**
     * Get a local instance of this object in another editing context.
     * @param editingContext The target editing context
     * @return An instance of this object in the target editing context
     */
    public EmailAlertForStudent localInstance(EOEditingContext editingContext)
    {
        return (EmailAlertForStudent)EOUtilities.localInstanceOfObject(
            editingContext, this);
    }


    // ----------------------------------------------------------
    /**
     * Get a list of changes between this object's current state and the
     * last committed version.
     * @return a dictionary of the changes that have not yet been committed
     */
    @SuppressWarnings("unchecked")
    public NSDictionary<String, Object> changedProperties()
    {
        return changesFromSnapshot(
            editingContext().committedSnapshotForObject(this));
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>id</code> value.
     * @return the value of the attribute
     */
    public Number id()
    {
        try
        {
            return (Number)EOUtilities.primaryKeyForObject(
                editingContext() , this).objectForKey("id");
        }
        catch (Exception e)
        {
            return er.extensions.eof.ERXConstant.ZeroInteger;
        }
    }

    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>byteCodingRating</code> value.
     * @return the value of the attribute
     */
    public byte byteCodingRating()
    {
        Integer returnValue =
            (Integer)storedValueForKey( "byteCodingRating" );
        return ( returnValue == null )
            ? 0
            : returnValue.byteValue();
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>byteCodingRating</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setByteCodingRating( byte value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setByteCodingRating("
                + value + "): was " + byteCodingRating() );
        }
        Integer actual =
            er.extensions.eof.ERXConstant.integerForInt( value );
            setByteCodingRatingRaw( actual );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>byteCodingRating</code> value.
     * @return the value of the attribute
     */
    public Integer byteCodingRatingRaw()
    {
        return (Integer)storedValueForKey( "byteCodingRating" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>byteCodingRating</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setByteCodingRatingRaw( Integer value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setByteCodingRatingRaw("
                + value + "): was " + byteCodingRatingRaw() );
        }
        takeStoredValueForKey( value, "byteCodingRating" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>byteCorrectnessRating</code> value.
     * @return the value of the attribute
     */
    public byte byteCorrectnessRating()
    {
        Integer returnValue =
            (Integer)storedValueForKey( "byteCorrectnessRating" );
        return ( returnValue == null )
            ? 0
            : returnValue.byteValue();
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>byteCorrectnessRating</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setByteCorrectnessRating( byte value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setByteCorrectnessRating("
                + value + "): was " + byteCorrectnessRating() );
        }
        Integer actual =
            er.extensions.eof.ERXConstant.integerForInt( value );
            setByteCorrectnessRatingRaw( actual );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>byteCorrectnessRating</code> value.
     * @return the value of the attribute
     */
    public Integer byteCorrectnessRatingRaw()
    {
        return (Integer)storedValueForKey( "byteCorrectnessRating" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>byteCorrectnessRating</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setByteCorrectnessRatingRaw( Integer value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setByteCorrectnessRatingRaw("
                + value + "): was " + byteCorrectnessRatingRaw() );
        }
        takeStoredValueForKey( value, "byteCorrectnessRating" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>byteStyleRating</code> value.
     * @return the value of the attribute
     */
    public byte byteStyleRating()
    {
        Integer returnValue =
            (Integer)storedValueForKey( "byteStyleRating" );
        return ( returnValue == null )
            ? 0
            : returnValue.byteValue();
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>byteStyleRating</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setByteStyleRating( byte value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setByteStyleRating("
                + value + "): was " + byteStyleRating() );
        }
        Integer actual =
            er.extensions.eof.ERXConstant.integerForInt( value );
            setByteStyleRatingRaw( actual );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>byteStyleRating</code> value.
     * @return the value of the attribute
     */
    public Integer byteStyleRatingRaw()
    {
        return (Integer)storedValueForKey( "byteStyleRating" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>byteStyleRating</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setByteStyleRatingRaw( Integer value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setByteStyleRatingRaw("
                + value + "): was " + byteStyleRatingRaw() );
        }
        takeStoredValueForKey( value, "byteStyleRating" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>byteTestingRating</code> value.
     * @return the value of the attribute
     */
    public byte byteTestingRating()
    {
        Integer returnValue =
            (Integer)storedValueForKey( "byteTestingRating" );
        return ( returnValue == null )
            ? 0
            : returnValue.byteValue();
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>byteTestingRating</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setByteTestingRating( byte value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setByteTestingRating("
                + value + "): was " + byteTestingRating() );
        }
        Integer actual =
            er.extensions.eof.ERXConstant.integerForInt( value );
            setByteTestingRatingRaw( actual );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>byteTestingRating</code> value.
     * @return the value of the attribute
     */
    public Integer byteTestingRatingRaw()
    {
        return (Integer)storedValueForKey( "byteTestingRating" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>byteTestingRating</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setByteTestingRatingRaw( Integer value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setByteTestingRatingRaw("
                + value + "): was " + byteTestingRatingRaw() );
        }
        takeStoredValueForKey( value, "byteTestingRating" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>sent</code> value.
     * @return the value of the attribute
     */
    public boolean sent()
    {
        Integer returnValue =
            (Integer)storedValueForKey( "sent" );
        return ( returnValue == null )
            ? false
            : ( returnValue.intValue() > 0 );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>sent</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setSent( boolean value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setSent("
                + value + "): was " + sent() );
        }
        Integer actual =
            er.extensions.eof.ERXConstant.integerForInt( value ? 1 : 0 );
            setSentRaw( actual );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>sent</code> value.
     * @return the value of the attribute
     */
    public Integer sentRaw()
    {
        return (Integer)storedValueForKey( "sent" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>sent</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setSentRaw( Integer value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setSentRaw("
                + value + "): was " + sentRaw() );
        }
        takeStoredValueForKey( value, "sent" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entity pointed to by the <code>alertOffering</code>
     * relationship.
     * @return the entity in the relationship
     */
    public org.webcat.schedulesheets.EmailAlertForAssignmentOffering alertOffering()
    {
        return (org.webcat.schedulesheets.EmailAlertForAssignmentOffering)storedValueForKey( "alertOffering" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>alertOffering</code>
     * relationship (DO NOT USE--instead, use
     * <code>setAlertOfferingRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void setAlertOffering( org.webcat.schedulesheets.EmailAlertForAssignmentOffering value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setAlertOffering("
                + value + "): was " + alertOffering() );
        }
        takeStoredValueForKey( value, "alertOffering" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>alertOffering</code>
     * relationship.  This method is a type-safe version of
     * <code>addObjectToBothSidesOfRelationshipWithKey()</code>.
     *
     * @param value The new entity to relate to
     */
    public void setAlertOfferingRelationship(
        org.webcat.schedulesheets.EmailAlertForAssignmentOffering value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setAlertOfferingRelationship("
                + value + "): was " + alertOffering() );
        }
        if ( value == null )
        {
            org.webcat.schedulesheets.EmailAlertForAssignmentOffering object = alertOffering();
            if ( object != null )
                removeObjectFromBothSidesOfRelationshipWithKey( object, "alertOffering" );
        }
        else
        {
            addObjectToBothSidesOfRelationshipWithKey( value, "alertOffering" );
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entity pointed to by the <code>submission</code>
     * relationship.
     * @return the entity in the relationship
     */
    public org.webcat.grader.Submission submission()
    {
        return (org.webcat.grader.Submission)storedValueForKey( "submission" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>submission</code>
     * relationship (DO NOT USE--instead, use
     * <code>setSubmissionRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void setSubmission( org.webcat.grader.Submission value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setSubmission("
                + value + "): was " + submission() );
        }
        takeStoredValueForKey( value, "submission" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>submission</code>
     * relationship.  This method is a type-safe version of
     * <code>addObjectToBothSidesOfRelationshipWithKey()</code>.
     *
     * @param value The new entity to relate to
     */
    public void setSubmissionRelationship(
        org.webcat.grader.Submission value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setSubmissionRelationship("
                + value + "): was " + submission() );
        }
        if ( value == null )
        {
            org.webcat.grader.Submission object = submission();
            if ( object != null )
                removeObjectFromBothSidesOfRelationshipWithKey( object, "submission" );
        }
        else
        {
            addObjectToBothSidesOfRelationshipWithKey( value, "submission" );
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entity pointed to by the <code>user</code>
     * relationship.
     * @return the entity in the relationship
     */
    public org.webcat.core.User user()
    {
        return (org.webcat.core.User)storedValueForKey( "user" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>user</code>
     * relationship (DO NOT USE--instead, use
     * <code>setUserRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void setUser( org.webcat.core.User value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setUser("
                + value + "): was " + user() );
        }
        takeStoredValueForKey( value, "user" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>user</code>
     * relationship.  This method is a type-safe version of
     * <code>addObjectToBothSidesOfRelationshipWithKey()</code>.
     *
     * @param value The new entity to relate to
     */
    public void setUserRelationship(
        org.webcat.core.User value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setUserRelationship("
                + value + "): was " + user() );
        }
        if ( value == null )
        {
            org.webcat.core.User object = user();
            if ( object != null )
                removeObjectFromBothSidesOfRelationshipWithKey( object, "user" );
        }
        else
        {
            addObjectToBothSidesOfRelationshipWithKey( value, "user" );
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a fetch specification.
     *
     * @param context The editing context to use
     * @param fspec The fetch specification to use
     *
     * @return an NSArray of the entities retrieved
     */
    @SuppressWarnings("unchecked")
    public static NSArray<EmailAlertForStudent> objectsWithFetchSpecification(
        EOEditingContext context,
        EOFetchSpecification fspec)
    {
        return context.objectsWithFetchSpecification(fspec);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve all objects of this type.
     *
     * @param context The editing context to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<EmailAlertForStudent> allObjects(
        EOEditingContext context)
    {
        return objectsMatchingQualifier(context, null, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a qualifier.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<EmailAlertForStudent> objectsMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier)
    {
        return objectsMatchingQualifier(context, qualifier, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a qualifier and sort orderings.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     * @param sortOrderings The sort orderings to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<EmailAlertForStudent> objectsMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier,
        NSArray<EOSortOrdering> sortOrderings)
    {
        WCFetchSpecification<EmailAlertForStudent> fspec =
            new WCFetchSpecification<EmailAlertForStudent>(
                ENTITY_NAME, qualifier, sortOrderings);
        fspec.setUsesDistinct(true);
        return objectsWithFetchSpecification(context, fspec);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the first object that matches a qualifier, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     * @param sortOrderings the sort orderings
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static EmailAlertForStudent firstObjectMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier,
        NSArray<EOSortOrdering> sortOrderings)
    {
        WCFetchSpecification<EmailAlertForStudent> fspec =
            new WCFetchSpecification<EmailAlertForStudent>(
                ENTITY_NAME, qualifier, sortOrderings);
        fspec.setUsesDistinct(true);
        fspec.setFetchLimit(1);
        NSArray<EmailAlertForStudent> objects =
            objectsWithFetchSpecification(context, fspec);
        return (objects.size() > 0)
            ? objects.get(0)
            : null;
    }


    // ----------------------------------------------------------
    /**
     * Retrieve a single object using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return the single entity that was retrieved
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static EmailAlertForStudent uniqueObjectMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier) throws EOUtilities.MoreThanOneException
    {
        NSArray<EmailAlertForStudent> objects =
            objectsMatchingQualifier(context, qualifier);
        if (objects.size() > 1)
        {
            String msg = "fetching EmailAlertForStudent";
            try
            {
                if (qualifier != null)
                {
                    msg += " where " + qualifier;
                }
                msg += ", result = " + objects;
            }
            catch (Exception e)
            {
                log.error("Exception building MoreThanOneException message, "
                    + "contents so far: " + msg, e);
            }
            throw new EOUtilities.MoreThanOneException(msg);
        }
        return (objects.size() > 0)
            ? objects.get(0)
            : null;
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<EmailAlertForStudent> objectsMatchingValues(
        EOEditingContext context,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value "
                + "corresponding to every key that was passed. Args = "
                + java.util.Arrays.toString(keysAndValues));
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (key == null)
            {
                throw new IllegalArgumentException(
                    "Found null where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }
            else if (!(key instanceof String))
            {
                throw new IllegalArgumentException(
                    "Found a " + key.getClass().getName() + " [" + key + "]"
                    + " where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }

            valueDictionary.setObjectForKey(value, (String)key);
        }

        return objectsMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a dictionary of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return an NSArray of the entities retrieved
     */
    @SuppressWarnings("unchecked")
    public static NSArray<EmailAlertForStudent> objectsMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
    {
        return EOUtilities.objectsMatchingValues(context, ENTITY_NAME,
            keysAndValues);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the first object that matches a set of keys and values, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param sortOrderings the sort orderings
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static EmailAlertForStudent firstObjectMatchingValues(
        EOEditingContext context,
        NSArray<EOSortOrdering> sortOrderings,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value "
                + "corresponding to every key that was passed. Args = "
                + java.util.Arrays.toString(keysAndValues));
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (key == null)
            {
                throw new IllegalArgumentException(
                    "Found null where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }
            else if (!(key instanceof String))
            {
                throw new IllegalArgumentException(
                    "Found a " + key.getClass().getName() + " [" + key + "]"
                    + " where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }

            valueDictionary.setObjectForKey(value, (String)key);
        }

        return firstObjectMatchingValues(
            context, sortOrderings, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieves the first object that matches a set of keys and values, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param sortOrderings the sort orderings
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static EmailAlertForStudent firstObjectMatchingValues(
        EOEditingContext context,
        NSArray<EOSortOrdering> sortOrderings,
        NSDictionary<String, Object> keysAndValues)
    {
        WCFetchSpecification<EmailAlertForStudent> fspec =
            new WCFetchSpecification<EmailAlertForStudent>(
                ENTITY_NAME,
                EOQualifier.qualifierToMatchAllValues(keysAndValues),
                sortOrderings);
        fspec.setFetchLimit(1);

        NSArray<EmailAlertForStudent> objects =
            objectsWithFetchSpecification( context, fspec );

        if ( objects.count() == 0 )
        {
            return null;
        }
        else
        {
            return objects.objectAtIndex(0);
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve a single object using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the single entity that was retrieved, or null if there was none
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static EmailAlertForStudent uniqueObjectMatchingValues(
        EOEditingContext context,
        Object... keysAndValues) throws EOUtilities.MoreThanOneException
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value "
                + "corresponding to every key that was passed. Args = "
                + java.util.Arrays.toString(keysAndValues));
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (key == null)
            {
                throw new IllegalArgumentException(
                    "Found null where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }
            else if (!(key instanceof String))
            {
                throw new IllegalArgumentException(
                    "Found a " + key.getClass().getName() + " [" + key + "]"
                    + " where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }

            valueDictionary.setObjectForKey(value, (String)key);
        }

        return uniqueObjectMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve an object using a dictionary of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the single entity that was retrieved, or null if there was none
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static EmailAlertForStudent uniqueObjectMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
        throws EOUtilities.MoreThanOneException
    {
        try
        {
            return (EmailAlertForStudent)EOUtilities.objectMatchingValues(
                context, ENTITY_NAME, keysAndValues);
        }
        catch (EOObjectNotAvailableException e)
        {
            return null;
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of all objects of this type.
     *
     * @param context The editing context to use
     *
     * @return the count of all objects
     */
    public static int countOfAllObjects(EOEditingContext context)
    {
        return countOfObjectsMatchingQualifier(context, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects that match a qualifier.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return the count of objects matching the qualifier
     */
    public static int countOfObjectsMatchingQualifier(
        EOEditingContext context, EOQualifier qualifier)
    {
        return ERXEOControlUtilities.objectCountWithQualifier(
                context, ENTITY_NAME, qualifier);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the count of objects that match the specified values
     */
    public static int countOfObjectsMatchingValues(
        EOEditingContext context,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value "
                + "corresponding to every key that was passed. Args = "
                + java.util.Arrays.toString(keysAndValues));
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (key == null)
            {
                throw new IllegalArgumentException(
                    "Found null where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }
            else if (!(key instanceof String))
            {
                throw new IllegalArgumentException(
                    "Found a " + key.getClass().getName() + " [" + key + "]"
                    + " where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }

            valueDictionary.setObjectForKey(value, (String)key);
        }

        return countOfObjectsMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects using a dictionary of keys and values to
     * match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the count of objects that matched the specified values
     */
    public static int countOfObjectsMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
    {
        return countOfObjectsMatchingQualifier(context,
                EOQualifier.qualifierToMatchAllValues(keysAndValues));
    }


    // ----------------------------------------------------------
    /**
     * Produce a string representation of this object.  This implementation
     * calls UserPresentableDescription(), which uses WebObjects' internal
     * mechanism to print out the visible fields of this object.  Normally,
     * subclasses would override userPresentableDescription() to change
     * the way the object is printed.
     *
     * @return A string representation of the object's value
     */
    public String toString()
    {
        return userPresentableDescription();
    }


    //~ Instance/static variables .............................................

    static Logger log = Logger.getLogger(EmailAlertForStudent.class);
}
