/*==========================================================================*\
 |  _ScheduleSheetSubmission.java
 |*-------------------------------------------------------------------------*|
 |  Created by eogenerator
 |  DO NOT EDIT.  Make changes to ScheduleSheetSubmission.java instead.
 |*-------------------------------------------------------------------------*|
 |  Copyright (C) 2006-2012 Virginia Tech
 |
 |  This file is part of Web-CAT.
 |
 |  Web-CAT is free software; you can redistribute it and/or modify
 |  it under the terms of the GNU Affero General Public License as published
 |  by the Free Software Foundation; either version 3 of the License, or
 |  (at your option) any later version.
 |
 |  Web-CAT is distributed in the hope that it will be useful,
 |  but WITHOUT ANY WARRANTY; without even the implied warranty of
 |  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 |  GNU General Public License for more details.
 |
 |  You should have received a copy of the GNU Affero General Public License
 |  along with Web-CAT; if not, see <http://www.gnu.org/licenses/>.
\*==========================================================================*/

package org.webcat.schedulesheets;

import com.webobjects.eoaccess.*;
import com.webobjects.eocontrol.*;
import com.webobjects.foundation.*;
import er.extensions.eof.ERXEOControlUtilities;
import er.extensions.eof.ERXKey;
import org.apache.log4j.Logger;
import org.webcat.core.EOBasedKeyGenerator;
import org.webcat.woextensions.WCFetchSpecification;

// -------------------------------------------------------------------------
/**
 * An automatically generated EOGenericRecord subclass.  DO NOT EDIT.
 * To change, use EOModeler, or make additions in
 * ScheduleSheetSubmission.java.
 *
 * @author Generated by eogenerator
 * @version version suppressed to control auto-generation
 */
public abstract class _ScheduleSheetSubmission
    extends org.webcat.core.EOBase
{
    //~ Constructors ..........................................................

    // ----------------------------------------------------------
    /**
     * Creates a new _ScheduleSheetSubmission object.
     */
    public _ScheduleSheetSubmission()
    {
        super();
    }


    // ----------------------------------------------------------
    /**
     * A static factory method for creating a new
     * ScheduleSheetSubmission object given required
     * attributes and relationships.
     * @param editingContext The context in which the new object will be
     * inserted
     * @param isSubmissionForGradingValue
     * @param partnerLinkValue
     * @return The newly created object
     */
    public static ScheduleSheetSubmission create(
        EOEditingContext editingContext,
        boolean isSubmissionForGradingValue,
        boolean partnerLinkValue
        )
    {
        ScheduleSheetSubmission eoObject = (ScheduleSheetSubmission)
            EOUtilities.createAndInsertInstance(
                editingContext,
                _ScheduleSheetSubmission.ENTITY_NAME);
        eoObject.setIsSubmissionForGrading(isSubmissionForGradingValue);
        eoObject.setPartnerLink(partnerLinkValue);
        return eoObject;
    }


    // ----------------------------------------------------------
    /**
     * Get a local instance of the given object in another editing context.
     * @param editingContext The target editing context
     * @param eo The object to import
     * @return An instance of the given object in the target editing context
     */
    public static ScheduleSheetSubmission localInstance(
        EOEditingContext editingContext, ScheduleSheetSubmission eo)
    {
        return (eo == null)
            ? null
            : (ScheduleSheetSubmission)EOUtilities.localInstanceOfObject(
                editingContext, eo);
    }


    // ----------------------------------------------------------
    /**
     * Look up an object by id number.  Assumes the editing
     * context is appropriately locked.
     * @param ec The editing context to use
     * @param id The id to look up
     * @return The object, or null if no such id exists
     */
    public static ScheduleSheetSubmission forId(
        EOEditingContext ec, int id)
    {
        ScheduleSheetSubmission obj = null;
        if (id > 0)
        {
            NSArray<ScheduleSheetSubmission> objects =
                objectsMatchingValues(ec, "id", new Integer(id));
            if (objects != null && objects.count() > 0)
            {
                obj = objects.objectAtIndex(0);
            }
        }
        return obj;
    }


    // ----------------------------------------------------------
    /**
     * Look up an object by id number.  Assumes the editing
     * context is appropriately locked.
     * @param ec The editing context to use
     * @param id The id to look up
     * @return The object, or null if no such id exists
     */
    public static ScheduleSheetSubmission forId(
        EOEditingContext ec, String id)
    {
        return forId(ec, er.extensions.foundation.ERXValueUtilities.intValue(id));
    }


    //~ Constants (for key names) .............................................

    // Attributes ---
    public static final String IS_SUBMISSION_FOR_GRADING_KEY = "isSubmissionForGrading";
    public static final ERXKey<Integer> isSubmissionForGrading =
        new ERXKey<Integer>(IS_SUBMISSION_FOR_GRADING_KEY);
    public static final String PARTNER_LINK_KEY = "partnerLink";
    public static final ERXKey<Integer> partnerLink =
        new ERXKey<Integer>(PARTNER_LINK_KEY);
    public static final String SUBMIT_NUMBER_KEY = "submitNumber";
    public static final ERXKey<Integer> submitNumber =
        new ERXKey<Integer>(SUBMIT_NUMBER_KEY);
    public static final String SUBMIT_TIME_KEY = "submitTime";
    public static final ERXKey<NSTimestamp> submitTime =
        new ERXKey<NSTimestamp>(SUBMIT_TIME_KEY);
    // To-one relationships ---
    public static final String ASSIGNMENT_OFFERING_KEY = "assignmentOffering";
    public static final ERXKey<org.webcat.schedulesheets.ScheduleSheetAssignmentOffering> assignmentOffering =
        new ERXKey<org.webcat.schedulesheets.ScheduleSheetAssignmentOffering>(ASSIGNMENT_OFFERING_KEY);
    public static final String PRIMARY_SUBMISSION_KEY = "primarySubmission";
    public static final ERXKey<org.webcat.schedulesheets.ScheduleSheetSubmission> primarySubmission =
        new ERXKey<org.webcat.schedulesheets.ScheduleSheetSubmission>(PRIMARY_SUBMISSION_KEY);
    public static final String SHEET_KEY = "sheet";
    public static final ERXKey<org.webcat.schedulesheets.ScheduleSheet> sheet =
        new ERXKey<org.webcat.schedulesheets.ScheduleSheet>(SHEET_KEY);
    public static final String USER_KEY = "user";
    public static final ERXKey<org.webcat.core.User> user =
        new ERXKey<org.webcat.core.User>(USER_KEY);
    // To-many relationships ---
    public static final String PARTNERED_SUBMISSIONS_KEY = "partneredSubmissions";
    public static final ERXKey<org.webcat.schedulesheets.ScheduleSheetSubmission> partneredSubmissions =
        new ERXKey<org.webcat.schedulesheets.ScheduleSheetSubmission>(PARTNERED_SUBMISSIONS_KEY);
    // Fetch specifications ---
    public static final String ENTITY_NAME = "ScheduleSheetSubmission";

    public transient final EOBasedKeyGenerator generateKey =
        new EOBasedKeyGenerator(this);


    //~ Methods ...............................................................

    // ----------------------------------------------------------
    /**
     * Get a local instance of this object in another editing context.
     * @param editingContext The target editing context
     * @return An instance of this object in the target editing context
     */
    public ScheduleSheetSubmission localInstance(EOEditingContext editingContext)
    {
        return (ScheduleSheetSubmission)EOUtilities.localInstanceOfObject(
            editingContext, this);
    }


    // ----------------------------------------------------------
    /**
     * Get a list of changes between this object's current state and the
     * last committed version.
     * @return a dictionary of the changes that have not yet been committed
     */
    @SuppressWarnings("unchecked")
    public NSDictionary<String, Object> changedProperties()
    {
        return changesFromSnapshot(
            editingContext().committedSnapshotForObject(this));
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>id</code> value.
     * @return the value of the attribute
     */
    public Number id()
    {
        try
        {
            return (Number)EOUtilities.primaryKeyForObject(
                editingContext() , this).objectForKey("id");
        }
        catch (Exception e)
        {
            return er.extensions.eof.ERXConstant.ZeroInteger;
        }
    }

    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>isSubmissionForGrading</code> value.
     * @return the value of the attribute
     */
    public boolean isSubmissionForGrading()
    {
        Integer returnValue =
            (Integer)storedValueForKey( "isSubmissionForGrading" );
        return ( returnValue == null )
            ? false
            : ( returnValue.intValue() > 0 );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>isSubmissionForGrading</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setIsSubmissionForGrading( boolean value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setIsSubmissionForGrading("
                + value + "): was " + isSubmissionForGrading() );
        }
        Integer actual =
            er.extensions.eof.ERXConstant.integerForInt( value ? 1 : 0 );
            setIsSubmissionForGradingRaw( actual );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>isSubmissionForGrading</code> value.
     * @return the value of the attribute
     */
    public Integer isSubmissionForGradingRaw()
    {
        return (Integer)storedValueForKey( "isSubmissionForGrading" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>isSubmissionForGrading</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setIsSubmissionForGradingRaw( Integer value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setIsSubmissionForGradingRaw("
                + value + "): was " + isSubmissionForGradingRaw() );
        }
        takeStoredValueForKey( value, "isSubmissionForGrading" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>partnerLink</code> value.
     * @return the value of the attribute
     */
    public boolean partnerLink()
    {
        Integer returnValue =
            (Integer)storedValueForKey( "partnerLink" );
        return ( returnValue == null )
            ? false
            : ( returnValue.intValue() > 0 );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>partnerLink</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setPartnerLink( boolean value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setPartnerLink("
                + value + "): was " + partnerLink() );
        }
        Integer actual =
            er.extensions.eof.ERXConstant.integerForInt( value ? 1 : 0 );
            setPartnerLinkRaw( actual );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>partnerLink</code> value.
     * @return the value of the attribute
     */
    public Integer partnerLinkRaw()
    {
        return (Integer)storedValueForKey( "partnerLink" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>partnerLink</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setPartnerLinkRaw( Integer value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setPartnerLinkRaw("
                + value + "): was " + partnerLinkRaw() );
        }
        takeStoredValueForKey( value, "partnerLink" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>submitNumber</code> value.
     * @return the value of the attribute
     */
    public int submitNumber()
    {
        Integer returnValue =
            (Integer)storedValueForKey( "submitNumber" );
        return ( returnValue == null )
            ? 0
            : returnValue.intValue();
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>submitNumber</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setSubmitNumber( int value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setSubmitNumber("
                + value + "): was " + submitNumber() );
        }
        Integer actual =
            er.extensions.eof.ERXConstant.integerForInt( value );
            setSubmitNumberRaw( actual );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>submitNumber</code> value.
     * @return the value of the attribute
     */
    public Integer submitNumberRaw()
    {
        return (Integer)storedValueForKey( "submitNumber" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>submitNumber</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setSubmitNumberRaw( Integer value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setSubmitNumberRaw("
                + value + "): was " + submitNumberRaw() );
        }
        takeStoredValueForKey( value, "submitNumber" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>submitTime</code> value.
     * @return the value of the attribute
     */
    public NSTimestamp submitTime()
    {
        return (NSTimestamp)storedValueForKey( "submitTime" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>submitTime</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setSubmitTime( NSTimestamp value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setSubmitTime("
                + value + "): was " + submitTime() );
        }
        takeStoredValueForKey( value, "submitTime" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entity pointed to by the <code>assignmentOffering</code>
     * relationship.
     * @return the entity in the relationship
     */
    public org.webcat.schedulesheets.ScheduleSheetAssignmentOffering assignmentOffering()
    {
        return (org.webcat.schedulesheets.ScheduleSheetAssignmentOffering)storedValueForKey( "assignmentOffering" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>assignmentOffering</code>
     * relationship (DO NOT USE--instead, use
     * <code>setAssignmentOfferingRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void setAssignmentOffering( org.webcat.schedulesheets.ScheduleSheetAssignmentOffering value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setAssignmentOffering("
                + value + "): was " + assignmentOffering() );
        }
        takeStoredValueForKey( value, "assignmentOffering" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>assignmentOffering</code>
     * relationship.  This method is a type-safe version of
     * <code>addObjectToBothSidesOfRelationshipWithKey()</code>.
     *
     * @param value The new entity to relate to
     */
    public void setAssignmentOfferingRelationship(
        org.webcat.schedulesheets.ScheduleSheetAssignmentOffering value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setAssignmentOfferingRelationship("
                + value + "): was " + assignmentOffering() );
        }
        if ( value == null )
        {
            org.webcat.schedulesheets.ScheduleSheetAssignmentOffering object = assignmentOffering();
            if ( object != null )
                removeObjectFromBothSidesOfRelationshipWithKey( object, "assignmentOffering" );
        }
        else
        {
            addObjectToBothSidesOfRelationshipWithKey( value, "assignmentOffering" );
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entity pointed to by the <code>primarySubmission</code>
     * relationship.
     * @return the entity in the relationship
     */
    public org.webcat.schedulesheets.ScheduleSheetSubmission primarySubmission()
    {
        return (org.webcat.schedulesheets.ScheduleSheetSubmission)storedValueForKey( "primarySubmission" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>primarySubmission</code>
     * relationship (DO NOT USE--instead, use
     * <code>setPrimarySubmissionRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void setPrimarySubmission( org.webcat.schedulesheets.ScheduleSheetSubmission value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setPrimarySubmission("
                + value + "): was " + primarySubmission() );
        }
        takeStoredValueForKey( value, "primarySubmission" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>primarySubmission</code>
     * relationship.  This method is a type-safe version of
     * <code>addObjectToBothSidesOfRelationshipWithKey()</code>.
     *
     * @param value The new entity to relate to
     */
    public void setPrimarySubmissionRelationship(
        org.webcat.schedulesheets.ScheduleSheetSubmission value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setPrimarySubmissionRelationship("
                + value + "): was " + primarySubmission() );
        }
        if ( value == null )
        {
            org.webcat.schedulesheets.ScheduleSheetSubmission object = primarySubmission();
            if ( object != null )
                removeObjectFromBothSidesOfRelationshipWithKey( object, "primarySubmission" );
        }
        else
        {
            addObjectToBothSidesOfRelationshipWithKey( value, "primarySubmission" );
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entity pointed to by the <code>sheet</code>
     * relationship.
     * @return the entity in the relationship
     */
    public org.webcat.schedulesheets.ScheduleSheet sheet()
    {
        return (org.webcat.schedulesheets.ScheduleSheet)storedValueForKey( "sheet" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>sheet</code>
     * relationship (DO NOT USE--instead, use
     * <code>setSheetRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void setSheet( org.webcat.schedulesheets.ScheduleSheet value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setSheet("
                + value + "): was " + sheet() );
        }
        takeStoredValueForKey( value, "sheet" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>sheet</code>
     * relationship.  This method is a type-safe version of
     * <code>addObjectToBothSidesOfRelationshipWithKey()</code>.
     *
     * @param value The new entity to relate to
     */
    public void setSheetRelationship(
        org.webcat.schedulesheets.ScheduleSheet value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setSheetRelationship("
                + value + "): was " + sheet() );
        }
        if ( value == null )
        {
            org.webcat.schedulesheets.ScheduleSheet object = sheet();
            if ( object != null )
                removeObjectFromBothSidesOfRelationshipWithKey( object, "sheet" );
        }
        else
        {
            addObjectToBothSidesOfRelationshipWithKey( value, "sheet" );
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entity pointed to by the <code>user</code>
     * relationship.
     * @return the entity in the relationship
     */
    public org.webcat.core.User user()
    {
        return (org.webcat.core.User)storedValueForKey( "user" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>user</code>
     * relationship (DO NOT USE--instead, use
     * <code>setUserRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void setUser( org.webcat.core.User value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setUser("
                + value + "): was " + user() );
        }
        takeStoredValueForKey( value, "user" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>user</code>
     * relationship.  This method is a type-safe version of
     * <code>addObjectToBothSidesOfRelationshipWithKey()</code>.
     *
     * @param value The new entity to relate to
     */
    public void setUserRelationship(
        org.webcat.core.User value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setUserRelationship("
                + value + "): was " + user() );
        }
        if ( value == null )
        {
            org.webcat.core.User object = user();
            if ( object != null )
                removeObjectFromBothSidesOfRelationshipWithKey( object, "user" );
        }
        else
        {
            addObjectToBothSidesOfRelationshipWithKey( value, "user" );
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entities pointed to by the <code>partneredSubmissions</code>
     * relationship.
     * @return an NSArray of the entities in the relationship
     */
    @SuppressWarnings("unchecked")
    public NSArray<org.webcat.schedulesheets.ScheduleSheetSubmission> partneredSubmissions()
    {
        return (NSArray<org.webcat.schedulesheets.ScheduleSheetSubmission>)
            storedValueForKey("partneredSubmissions");
    }


    // ----------------------------------------------------------
    /**
     * Replace the list of entities pointed to by the
     * <code>partneredSubmissions</code> relationship.
     *
     * @param value The new set of entities to relate to
     */
    public void setPartneredSubmissions(
        NSMutableArray<org.webcat.schedulesheets.ScheduleSheetSubmission>  value)
    {
        if (log.isDebugEnabled())
        {
            log.debug("setPartneredSubmissions("
                + value + "): was " + partneredSubmissions());
        }
        takeStoredValueForKey(value, "partneredSubmissions");
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>partneredSubmissions</code>
     * relationship (DO NOT USE--instead, use
     * <code>addToPartneredSubmissionsRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void addToPartneredSubmissions( org.webcat.schedulesheets.ScheduleSheetSubmission value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToPartneredSubmissions("
                + value + "): was " + partneredSubmissions() );
        }
        NSMutableArray<org.webcat.schedulesheets.ScheduleSheetSubmission> array =
            (NSMutableArray<org.webcat.schedulesheets.ScheduleSheetSubmission>)partneredSubmissions();
        willChange();
        array.addObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>partneredSubmissions</code>
     * relationship (DO NOT USE--instead, use
     * <code>removeFromPartneredSubmissionsRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromPartneredSubmissions( org.webcat.schedulesheets.ScheduleSheetSubmission value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "RemoveFromPartneredSubmissions("
                + value + "): was " + partneredSubmissions() );
        }
        NSMutableArray<org.webcat.schedulesheets.ScheduleSheetSubmission> array =
            (NSMutableArray<org.webcat.schedulesheets.ScheduleSheetSubmission>)partneredSubmissions();
        willChange();
        array.removeObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>partneredSubmissions</code>
     * relationship.
     *
     * @param value The new entity to relate to
     */
    public void addToPartneredSubmissionsRelationship( org.webcat.schedulesheets.ScheduleSheetSubmission value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToPartneredSubmissionsRelationship("
                + value + "): was " + partneredSubmissions() );
        }
        addObjectToBothSidesOfRelationshipWithKey(
            value, "partneredSubmissions" );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>partneredSubmissions</code>
     * relationship.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromPartneredSubmissionsRelationship( org.webcat.schedulesheets.ScheduleSheetSubmission value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "removeFromPartneredSubmissionsRelationship("
                + value + "): was " + partneredSubmissions() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "partneredSubmissions" );
    }


    // ----------------------------------------------------------
    /**
     * Create a brand new object that is a member of the
     * <code>partneredSubmissions</code> relationship.
     *
     * @return The new entity
     */
    public org.webcat.schedulesheets.ScheduleSheetSubmission createPartneredSubmissionsRelationship()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "createPartneredSubmissionsRelationship()" );
        }
        EOClassDescription eoClassDesc = EOClassDescription
            .classDescriptionForEntityName( "ScheduleSheetSubmission" );
        EOEnterpriseObject eoObject = eoClassDesc
            .createInstanceWithEditingContext( editingContext(), null );
        editingContext().insertObject( eoObject );
        addObjectToBothSidesOfRelationshipWithKey(
            eoObject, "partneredSubmissions" );
        return (org.webcat.schedulesheets.ScheduleSheetSubmission)eoObject;
    }


    // ----------------------------------------------------------
    /**
     * Remove and then delete a specific entity that is a member of the
     * <code>partneredSubmissions</code> relationship.
     *
     * @param value The entity to remove from the relationship and then delete
     */
    public void deletePartneredSubmissionsRelationship( org.webcat.schedulesheets.ScheduleSheetSubmission value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deletePartneredSubmissionsRelationship("
                + value + "): was " + partneredSubmissions() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "partneredSubmissions" );
        editingContext().deleteObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove (and then delete, if owned) all entities that are members of the
     * <code>partneredSubmissions</code> relationship.
     */
    public void deleteAllPartneredSubmissionsRelationships()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteAllPartneredSubmissionsRelationships(): was "
                + partneredSubmissions() );
        }
        for (org.webcat.schedulesheets.ScheduleSheetSubmission object : partneredSubmissions())
        {
            deletePartneredSubmissionsRelationship(object);
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a fetch specification.
     *
     * @param context The editing context to use
     * @param fspec The fetch specification to use
     *
     * @return an NSArray of the entities retrieved
     */
    @SuppressWarnings("unchecked")
    public static NSArray<ScheduleSheetSubmission> objectsWithFetchSpecification(
        EOEditingContext context,
        EOFetchSpecification fspec)
    {
        return context.objectsWithFetchSpecification(fspec);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve all objects of this type.
     *
     * @param context The editing context to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<ScheduleSheetSubmission> allObjects(
        EOEditingContext context)
    {
        return objectsMatchingQualifier(context, null, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a qualifier.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<ScheduleSheetSubmission> objectsMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier)
    {
        return objectsMatchingQualifier(context, qualifier, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a qualifier and sort orderings.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     * @param sortOrderings The sort orderings to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<ScheduleSheetSubmission> objectsMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier,
        NSArray<EOSortOrdering> sortOrderings)
    {
        WCFetchSpecification<ScheduleSheetSubmission> fspec =
            new WCFetchSpecification<ScheduleSheetSubmission>(
                ENTITY_NAME, qualifier, sortOrderings);
        fspec.setUsesDistinct(true);
        return objectsWithFetchSpecification(context, fspec);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the first object that matches a qualifier, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     * @param sortOrderings the sort orderings
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static ScheduleSheetSubmission firstObjectMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier,
        NSArray<EOSortOrdering> sortOrderings)
    {
        WCFetchSpecification<ScheduleSheetSubmission> fspec =
            new WCFetchSpecification<ScheduleSheetSubmission>(
                ENTITY_NAME, qualifier, sortOrderings);
        fspec.setUsesDistinct(true);
        fspec.setFetchLimit(1);
        NSArray<ScheduleSheetSubmission> objects =
            objectsWithFetchSpecification(context, fspec);
        return (objects.size() > 0)
            ? objects.get(0)
            : null;
    }


    // ----------------------------------------------------------
    /**
     * Retrieve a single object using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return the single entity that was retrieved
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static ScheduleSheetSubmission uniqueObjectMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier) throws EOUtilities.MoreThanOneException
    {
        NSArray<ScheduleSheetSubmission> objects =
            objectsMatchingQualifier(context, qualifier);
        if (objects.size() > 1)
        {
            String msg = "fetching ScheduleSheetSubmission";
            try
            {
                if (qualifier != null)
                {
                    msg += " where " + qualifier;
                }
                msg += ", result = " + objects;
            }
            catch (Exception e)
            {
                log.error("Exception building MoreThanOneException message, "
                    + "contents so far: " + msg, e);
            }
            throw new EOUtilities.MoreThanOneException(msg);
        }
        return (objects.size() > 0)
            ? objects.get(0)
            : null;
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<ScheduleSheetSubmission> objectsMatchingValues(
        EOEditingContext context,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value "
                + "corresponding to every key that was passed. Args = "
                + java.util.Arrays.toString(keysAndValues));
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (key == null)
            {
                throw new IllegalArgumentException(
                    "Found null where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }
            else if (!(key instanceof String))
            {
                throw new IllegalArgumentException(
                    "Found a " + key.getClass().getName() + " [" + key + "]"
                    + " where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }

            valueDictionary.setObjectForKey(value, key);
        }

        return objectsMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a dictionary of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return an NSArray of the entities retrieved
     */
    @SuppressWarnings("unchecked")
    public static NSArray<ScheduleSheetSubmission> objectsMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
    {
        return EOUtilities.objectsMatchingValues(context, ENTITY_NAME,
            keysAndValues);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the first object that matches a set of keys and values, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param sortOrderings the sort orderings
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static ScheduleSheetSubmission firstObjectMatchingValues(
        EOEditingContext context,
        NSArray<EOSortOrdering> sortOrderings,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value "
                + "corresponding to every key that was passed. Args = "
                + java.util.Arrays.toString(keysAndValues));
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (key == null)
            {
                throw new IllegalArgumentException(
                    "Found null where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }
            else if (!(key instanceof String))
            {
                throw new IllegalArgumentException(
                    "Found a " + key.getClass().getName() + " [" + key + "]"
                    + " where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }

            valueDictionary.setObjectForKey(value, key);
        }

        return firstObjectMatchingValues(
            context, sortOrderings, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieves the first object that matches a set of keys and values, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param sortOrderings the sort orderings
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static ScheduleSheetSubmission firstObjectMatchingValues(
        EOEditingContext context,
        NSArray<EOSortOrdering> sortOrderings,
        NSDictionary<String, Object> keysAndValues)
    {
        WCFetchSpecification<ScheduleSheetSubmission> fspec =
            new WCFetchSpecification<ScheduleSheetSubmission>(
                ENTITY_NAME,
                EOQualifier.qualifierToMatchAllValues(keysAndValues),
                sortOrderings);
        fspec.setFetchLimit(1);

        NSArray<ScheduleSheetSubmission> objects =
            objectsWithFetchSpecification( context, fspec );

        if ( objects.count() == 0 )
        {
            return null;
        }
        else
        {
            return objects.objectAtIndex(0);
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve a single object using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the single entity that was retrieved, or null if there was none
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static ScheduleSheetSubmission uniqueObjectMatchingValues(
        EOEditingContext context,
        Object... keysAndValues) throws EOUtilities.MoreThanOneException
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value "
                + "corresponding to every key that was passed. Args = "
                + java.util.Arrays.toString(keysAndValues));
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (key == null)
            {
                throw new IllegalArgumentException(
                    "Found null where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }
            else if (!(key instanceof String))
            {
                throw new IllegalArgumentException(
                    "Found a " + key.getClass().getName() + " [" + key + "]"
                    + " where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }

            valueDictionary.setObjectForKey(value, key);
        }

        return uniqueObjectMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve an object using a dictionary of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the single entity that was retrieved, or null if there was none
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static ScheduleSheetSubmission uniqueObjectMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
        throws EOUtilities.MoreThanOneException
    {
        try
        {
            return (ScheduleSheetSubmission)EOUtilities.objectMatchingValues(
                context, ENTITY_NAME, keysAndValues);
        }
        catch (EOObjectNotAvailableException e)
        {
            return null;
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of all objects of this type.
     *
     * @param context The editing context to use
     *
     * @return the count of all objects
     */
    public static int countOfAllObjects(EOEditingContext context)
    {
        return countOfObjectsMatchingQualifier(context, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects that match a qualifier.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return the count of objects matching the qualifier
     */
    public static int countOfObjectsMatchingQualifier(
        EOEditingContext context, EOQualifier qualifier)
    {
        return ERXEOControlUtilities.objectCountWithQualifier(
                context, ENTITY_NAME, qualifier);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the count of objects that match the specified values
     */
    public static int countOfObjectsMatchingValues(
        EOEditingContext context,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value "
                + "corresponding to every key that was passed. Args = "
                + java.util.Arrays.toString(keysAndValues));
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (key == null)
            {
                throw new IllegalArgumentException(
                    "Found null where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }
            else if (!(key instanceof String))
            {
                throw new IllegalArgumentException(
                    "Found a " + key.getClass().getName() + " [" + key + "]"
                    + " where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }

            valueDictionary.setObjectForKey(value, key);
        }

        return countOfObjectsMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects using a dictionary of keys and values to
     * match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the count of objects that matched the specified values
     */
    public static int countOfObjectsMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
    {
        return countOfObjectsMatchingQualifier(context,
                EOQualifier.qualifierToMatchAllValues(keysAndValues));
    }


    // ----------------------------------------------------------
    /**
     * Produce a string representation of this object.  This implementation
     * calls UserPresentableDescription(), which uses WebObjects' internal
     * mechanism to print out the visible fields of this object.  Normally,
     * subclasses would override userPresentableDescription() to change
     * the way the object is printed.
     *
     * @return A string representation of the object's value
     */
    public String toString()
    {
        return userPresentableDescription();
    }


    //~ Instance/static variables .............................................

    static Logger log = Logger.getLogger(ScheduleSheetSubmission.class);
}
