/*==========================================================================*\
 |  _ScheduleSheet.java
 |*-------------------------------------------------------------------------*|
 |  Created by eogenerator
 |  DO NOT EDIT.  Make changes to ScheduleSheet.java instead.
 |*-------------------------------------------------------------------------*|
 |  Copyright (C) 2006-2012 Virginia Tech
 |
 |  This file is part of Web-CAT.
 |
 |  Web-CAT is free software; you can redistribute it and/or modify
 |  it under the terms of the GNU Affero General Public License as published
 |  by the Free Software Foundation; either version 3 of the License, or
 |  (at your option) any later version.
 |
 |  Web-CAT is distributed in the hope that it will be useful,
 |  but WITHOUT ANY WARRANTY; without even the implied warranty of
 |  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 |  GNU General Public License for more details.
 |
 |  You should have received a copy of the GNU Affero General Public License
 |  along with Web-CAT; if not, see <http://www.gnu.org/licenses/>.
\*==========================================================================*/

package org.webcat.schedulesheets;

import com.webobjects.eoaccess.*;
import com.webobjects.eocontrol.*;
import com.webobjects.foundation.*;
import er.extensions.eof.ERXEOControlUtilities;
import er.extensions.eof.ERXKey;
import org.apache.log4j.Logger;
import org.webcat.core.EOBasedKeyGenerator;
import org.webcat.woextensions.WCFetchSpecification;

// -------------------------------------------------------------------------
/**
 * An automatically generated EOGenericRecord subclass.  DO NOT EDIT.
 * To change, use EOModeler, or make additions in
 * ScheduleSheet.java.
 *
 * @author Generated by eogenerator
 * @version version suppressed to control auto-generation
 */
public abstract class _ScheduleSheet
    extends org.webcat.core.EOBase
{
    //~ Constructors ..........................................................

    // ----------------------------------------------------------
    /**
     * Creates a new _ScheduleSheet object.
     */
    public _ScheduleSheet()
    {
        super();
    }


    // ----------------------------------------------------------
    /**
     * A static factory method for creating a new
     * ScheduleSheet object given required
     * attributes and relationships.
     * @param editingContext The context in which the new object will be
     * inserted
     * @return The newly created object
     */
    public static ScheduleSheet create(
        EOEditingContext editingContext
        )
    {
        ScheduleSheet eoObject = (ScheduleSheet)
            EOUtilities.createAndInsertInstance(
                editingContext,
                _ScheduleSheet.ENTITY_NAME);
        return eoObject;
    }


    // ----------------------------------------------------------
    /**
     * Get a local instance of the given object in another editing context.
     * @param editingContext The target editing context
     * @param eo The object to import
     * @return An instance of the given object in the target editing context
     */
    public static ScheduleSheet localInstance(
        EOEditingContext editingContext, ScheduleSheet eo)
    {
        return (eo == null)
            ? null
            : (ScheduleSheet)EOUtilities.localInstanceOfObject(
                editingContext, eo);
    }


    // ----------------------------------------------------------
    /**
     * Look up an object by id number.  Assumes the editing
     * context is appropriately locked.
     * @param ec The editing context to use
     * @param id The id to look up
     * @return The object, or null if no such id exists
     */
    public static ScheduleSheet forId(
        EOEditingContext ec, int id)
    {
        ScheduleSheet obj = null;
        if (id > 0)
        {
            NSArray<ScheduleSheet> objects =
                objectsMatchingValues(ec, "id", new Integer(id));
            if (objects != null && objects.count() > 0)
            {
                obj = objects.objectAtIndex(0);
            }
        }
        return obj;
    }


    // ----------------------------------------------------------
    /**
     * Look up an object by id number.  Assumes the editing
     * context is appropriately locked.
     * @param ec The editing context to use
     * @param id The id to look up
     * @return The object, or null if no such id exists
     */
    public static ScheduleSheet forId(
        EOEditingContext ec, String id)
    {
        return forId(ec, er.extensions.foundation.ERXValueUtilities.intValue(id));
    }


    //~ Constants (for key names) .............................................

    // Attributes ---
    public static final String COMMENT_FORMAT_KEY = "commentFormat";
    public static final ERXKey<Integer> commentFormat =
        new ERXKey<Integer>(COMMENT_FORMAT_KEY);
    public static final String COMMENTS_KEY = "comments";
    public static final ERXKey<String> comments =
        new ERXKey<String>(COMMENTS_KEY);
    public static final String LAST_UPDATED_KEY = "lastUpdated";
    public static final ERXKey<NSTimestamp> lastUpdated =
        new ERXKey<NSTimestamp>(LAST_UPDATED_KEY);
    public static final String SCORE_KEY = "score";
    public static final ERXKey<Double> score =
        new ERXKey<Double>(SCORE_KEY);
    public static final String STATUS_KEY = "status";
    public static final ERXKey<Integer> status =
        new ERXKey<Integer>(STATUS_KEY);
    public static final String TA_SCORE_KEY = "taScore";
    public static final ERXKey<Double> taScore =
        new ERXKey<Double>(TA_SCORE_KEY);
    public static final String TOOL_SCORE_KEY = "toolScore";
    public static final ERXKey<Double> toolScore =
        new ERXKey<Double>(TOOL_SCORE_KEY);
    // To-one relationships ---
    // To-many relationships ---
    public static final String COMPONENT_FEATURES_KEY = "componentFeatures";
    public static final ERXKey<org.webcat.schedulesheets.ComponentFeature> componentFeatures =
        new ERXKey<org.webcat.schedulesheets.ComponentFeature>(COMPONENT_FEATURES_KEY);
    public static final String FEEDBACK_ITEMS_KEY = "feedbackItems";
    public static final ERXKey<org.webcat.schedulesheets.SheetFeedbackItem> feedbackItems =
        new ERXKey<org.webcat.schedulesheets.SheetFeedbackItem>(FEEDBACK_ITEMS_KEY);
    public static final String SUBMISSIONS_KEY = "submissions";
    public static final ERXKey<org.webcat.schedulesheets.ScheduleSheetSubmission> submissions =
        new ERXKey<org.webcat.schedulesheets.ScheduleSheetSubmission>(SUBMISSIONS_KEY);
    // Fetch specifications ---
    public static final String ENTITY_NAME = "ScheduleSheet";

    public transient final EOBasedKeyGenerator generateKey =
        new EOBasedKeyGenerator(this);


    //~ Methods ...............................................................

    // ----------------------------------------------------------
    /**
     * Get a local instance of this object in another editing context.
     * @param editingContext The target editing context
     * @return An instance of this object in the target editing context
     */
    public ScheduleSheet localInstance(EOEditingContext editingContext)
    {
        return (ScheduleSheet)EOUtilities.localInstanceOfObject(
            editingContext, this);
    }


    // ----------------------------------------------------------
    /**
     * Get a list of changes between this object's current state and the
     * last committed version.
     * @return a dictionary of the changes that have not yet been committed
     */
    @SuppressWarnings("unchecked")
    public NSDictionary<String, Object> changedProperties()
    {
        return changesFromSnapshot(
            editingContext().committedSnapshotForObject(this));
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>id</code> value.
     * @return the value of the attribute
     */
    public Number id()
    {
        try
        {
            return (Number)EOUtilities.primaryKeyForObject(
                editingContext() , this).objectForKey("id");
        }
        catch (Exception e)
        {
            return er.extensions.eof.ERXConstant.ZeroInteger;
        }
    }

    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>commentFormat</code> value.
     * @return the value of the attribute
     */
    public byte commentFormat()
    {
        Integer returnValue =
            (Integer)storedValueForKey( "commentFormat" );
        return ( returnValue == null )
            ? 0
            : returnValue.byteValue();
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>commentFormat</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setCommentFormat( byte value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setCommentFormat("
                + value + "): was " + commentFormat() );
        }
        Integer actual =
            er.extensions.eof.ERXConstant.integerForInt( value );
            setCommentFormatRaw( actual );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>commentFormat</code> value.
     * @return the value of the attribute
     */
    public Integer commentFormatRaw()
    {
        return (Integer)storedValueForKey( "commentFormat" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>commentFormat</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setCommentFormatRaw( Integer value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setCommentFormatRaw("
                + value + "): was " + commentFormatRaw() );
        }
        takeStoredValueForKey( value, "commentFormat" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>comments</code> value.
     * @return the value of the attribute
     */
    public String comments()
    {
        return (String)storedValueForKey( "comments" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>comments</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setComments( String value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setComments("
                + value + "): was " + comments() );
        }
        takeStoredValueForKey( value, "comments" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>lastUpdated</code> value.
     * @return the value of the attribute
     */
    public NSTimestamp lastUpdated()
    {
        return (NSTimestamp)storedValueForKey( "lastUpdated" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>lastUpdated</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setLastUpdated( NSTimestamp value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setLastUpdated("
                + value + "): was " + lastUpdated() );
        }
        takeStoredValueForKey( value, "lastUpdated" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>score</code> value.
     * @return the value of the attribute
     */
    public double score()
    {
        Double returnValue =
            (Double)storedValueForKey( "score" );
        return ( returnValue == null )
            ? 0.0
            : returnValue.doubleValue();
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>score</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setScore( double value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setScore("
                + value + "): was " + score() );
        }
        Double actual =
            new Double( value );
            setScoreRaw( actual );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>score</code> value.
     * @return the value of the attribute
     */
    public Double scoreRaw()
    {
        return (Double)storedValueForKey( "score" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>score</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setScoreRaw( Double value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setScoreRaw("
                + value + "): was " + scoreRaw() );
        }
        takeStoredValueForKey( value, "score" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>status</code> value.
     * @return the value of the attribute
     */
    public byte status()
    {
        Integer returnValue =
            (Integer)storedValueForKey( "status" );
        return ( returnValue == null )
            ? org.webcat.core.Status.TO_DO
            : returnValue.byteValue();
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>status</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setStatus( byte value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setStatus("
                + value + "): was " + status() );
        }
        Integer actual =
            er.extensions.eof.ERXConstant.integerForInt( value );
            setStatusRaw( actual );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>status</code> value.
     * @return the value of the attribute
     */
    public Integer statusRaw()
    {
        return (Integer)storedValueForKey( "status" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>status</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setStatusRaw( Integer value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setStatusRaw("
                + value + "): was " + statusRaw() );
        }
        takeStoredValueForKey( value, "status" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>taScore</code> value.
     * @return the value of the attribute
     */
    public double taScore()
    {
        Double returnValue =
            (Double)storedValueForKey( "taScore" );
        return ( returnValue == null )
            ? 0.0
            : returnValue.doubleValue();
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>taScore</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setTaScore( double value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setTaScore("
                + value + "): was " + taScore() );
        }
        Double actual =
            new Double( value );
            setTaScoreRaw( actual );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>taScore</code> value.
     * @return the value of the attribute
     */
    public Double taScoreRaw()
    {
        return (Double)storedValueForKey( "taScore" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>taScore</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setTaScoreRaw( Double value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setTaScoreRaw("
                + value + "): was " + taScoreRaw() );
        }
        takeStoredValueForKey( value, "taScore" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>toolScore</code> value.
     * @return the value of the attribute
     */
    public double toolScore()
    {
        Double returnValue =
            (Double)storedValueForKey( "toolScore" );
        return ( returnValue == null )
            ? 0.0
            : returnValue.doubleValue();
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>toolScore</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setToolScore( double value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setToolScore("
                + value + "): was " + toolScore() );
        }
        Double actual =
            new Double( value );
            setToolScoreRaw( actual );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>toolScore</code> value.
     * @return the value of the attribute
     */
    public Double toolScoreRaw()
    {
        return (Double)storedValueForKey( "toolScore" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>toolScore</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setToolScoreRaw( Double value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setToolScoreRaw("
                + value + "): was " + toolScoreRaw() );
        }
        takeStoredValueForKey( value, "toolScore" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entities pointed to by the <code>componentFeatures</code>
     * relationship.
     * @return an NSArray of the entities in the relationship
     */
    @SuppressWarnings("unchecked")
    public NSArray<org.webcat.schedulesheets.ComponentFeature> componentFeatures()
    {
        return (NSArray)storedValueForKey( "componentFeatures" );
    }


    // ----------------------------------------------------------
    /**
     * Replace the list of entities pointed to by the
     * <code>componentFeatures</code> relationship.
     *
     * @param value The new set of entities to relate to
     */
    public void setComponentFeatures( NSMutableArray<org.webcat.schedulesheets.ComponentFeature>  value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setComponentFeatures("
                + value + "): was " + componentFeatures() );
        }
        takeStoredValueForKey( value, "componentFeatures" );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>componentFeatures</code>
     * relationship (DO NOT USE--instead, use
     * <code>addToComponentFeaturesRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void addToComponentFeatures( org.webcat.schedulesheets.ComponentFeature value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToComponentFeatures("
                + value + "): was " + componentFeatures() );
        }
        NSMutableArray<org.webcat.schedulesheets.ComponentFeature> array =
            (NSMutableArray<org.webcat.schedulesheets.ComponentFeature>)componentFeatures();
        willChange();
        array.addObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>componentFeatures</code>
     * relationship (DO NOT USE--instead, use
     * <code>removeFromComponentFeaturesRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromComponentFeatures( org.webcat.schedulesheets.ComponentFeature value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "RemoveFromComponentFeatures("
                + value + "): was " + componentFeatures() );
        }
        NSMutableArray<org.webcat.schedulesheets.ComponentFeature> array =
            (NSMutableArray<org.webcat.schedulesheets.ComponentFeature>)componentFeatures();
        willChange();
        array.removeObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>componentFeatures</code>
     * relationship.
     *
     * @param value The new entity to relate to
     */
    public void addToComponentFeaturesRelationship( org.webcat.schedulesheets.ComponentFeature value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToComponentFeaturesRelationship("
                + value + "): was " + componentFeatures() );
        }
        addObjectToBothSidesOfRelationshipWithKey(
            value, "componentFeatures" );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>componentFeatures</code>
     * relationship.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromComponentFeaturesRelationship( org.webcat.schedulesheets.ComponentFeature value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "removeFromComponentFeaturesRelationship("
                + value + "): was " + componentFeatures() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "componentFeatures" );
    }


    // ----------------------------------------------------------
    /**
     * Create a brand new object that is a member of the
     * <code>componentFeatures</code> relationship.
     *
     * @return The new entity
     */
    public org.webcat.schedulesheets.ComponentFeature createComponentFeaturesRelationship()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "createComponentFeaturesRelationship()" );
        }
        EOClassDescription eoClassDesc = EOClassDescription
            .classDescriptionForEntityName( "ComponentFeature" );
        EOEnterpriseObject eoObject = eoClassDesc
            .createInstanceWithEditingContext( editingContext(), null );
        editingContext().insertObject( eoObject );
        addObjectToBothSidesOfRelationshipWithKey(
            eoObject, "componentFeatures" );
        return (org.webcat.schedulesheets.ComponentFeature)eoObject;
    }


    // ----------------------------------------------------------
    /**
     * Remove and then delete a specific entity that is a member of the
     * <code>componentFeatures</code> relationship.
     *
     * @param value The entity to remove from the relationship and then delete
     */
    public void deleteComponentFeaturesRelationship( org.webcat.schedulesheets.ComponentFeature value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteComponentFeaturesRelationship("
                + value + "): was " + componentFeatures() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "componentFeatures" );
        editingContext().deleteObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove (and then delete, if owned) all entities that are members of the
     * <code>componentFeatures</code> relationship.
     */
    public void deleteAllComponentFeaturesRelationships()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteAllComponentFeaturesRelationships(): was "
                + componentFeatures() );
        }
        for (org.webcat.schedulesheets.ComponentFeature object : componentFeatures())
        {
            deleteComponentFeaturesRelationship(object);
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entities pointed to by the <code>feedbackItems</code>
     * relationship.
     * @return an NSArray of the entities in the relationship
     */
    @SuppressWarnings("unchecked")
    public NSArray<org.webcat.schedulesheets.SheetFeedbackItem> feedbackItems()
    {
        return (NSArray)storedValueForKey( "feedbackItems" );
    }


    // ----------------------------------------------------------
    /**
     * Replace the list of entities pointed to by the
     * <code>feedbackItems</code> relationship.
     *
     * @param value The new set of entities to relate to
     */
    public void setFeedbackItems( NSMutableArray<org.webcat.schedulesheets.SheetFeedbackItem>  value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setFeedbackItems("
                + value + "): was " + feedbackItems() );
        }
        takeStoredValueForKey( value, "feedbackItems" );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>feedbackItems</code>
     * relationship (DO NOT USE--instead, use
     * <code>addToFeedbackItemsRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void addToFeedbackItems( org.webcat.schedulesheets.SheetFeedbackItem value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToFeedbackItems("
                + value + "): was " + feedbackItems() );
        }
        NSMutableArray<org.webcat.schedulesheets.SheetFeedbackItem> array =
            (NSMutableArray<org.webcat.schedulesheets.SheetFeedbackItem>)feedbackItems();
        willChange();
        array.addObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>feedbackItems</code>
     * relationship (DO NOT USE--instead, use
     * <code>removeFromFeedbackItemsRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromFeedbackItems( org.webcat.schedulesheets.SheetFeedbackItem value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "RemoveFromFeedbackItems("
                + value + "): was " + feedbackItems() );
        }
        NSMutableArray<org.webcat.schedulesheets.SheetFeedbackItem> array =
            (NSMutableArray<org.webcat.schedulesheets.SheetFeedbackItem>)feedbackItems();
        willChange();
        array.removeObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>feedbackItems</code>
     * relationship.
     *
     * @param value The new entity to relate to
     */
    public void addToFeedbackItemsRelationship( org.webcat.schedulesheets.SheetFeedbackItem value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToFeedbackItemsRelationship("
                + value + "): was " + feedbackItems() );
        }
        addObjectToBothSidesOfRelationshipWithKey(
            value, "feedbackItems" );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>feedbackItems</code>
     * relationship.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromFeedbackItemsRelationship( org.webcat.schedulesheets.SheetFeedbackItem value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "removeFromFeedbackItemsRelationship("
                + value + "): was " + feedbackItems() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "feedbackItems" );
    }


    // ----------------------------------------------------------
    /**
     * Create a brand new object that is a member of the
     * <code>feedbackItems</code> relationship.
     *
     * @return The new entity
     */
    public org.webcat.schedulesheets.SheetFeedbackItem createFeedbackItemsRelationship()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "createFeedbackItemsRelationship()" );
        }
        EOClassDescription eoClassDesc = EOClassDescription
            .classDescriptionForEntityName( "SheetFeedbackItem" );
        EOEnterpriseObject eoObject = eoClassDesc
            .createInstanceWithEditingContext( editingContext(), null );
        editingContext().insertObject( eoObject );
        addObjectToBothSidesOfRelationshipWithKey(
            eoObject, "feedbackItems" );
        return (org.webcat.schedulesheets.SheetFeedbackItem)eoObject;
    }


    // ----------------------------------------------------------
    /**
     * Remove and then delete a specific entity that is a member of the
     * <code>feedbackItems</code> relationship.
     *
     * @param value The entity to remove from the relationship and then delete
     */
    public void deleteFeedbackItemsRelationship( org.webcat.schedulesheets.SheetFeedbackItem value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteFeedbackItemsRelationship("
                + value + "): was " + feedbackItems() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "feedbackItems" );
        editingContext().deleteObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove (and then delete, if owned) all entities that are members of the
     * <code>feedbackItems</code> relationship.
     */
    public void deleteAllFeedbackItemsRelationships()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteAllFeedbackItemsRelationships(): was "
                + feedbackItems() );
        }
        for (org.webcat.schedulesheets.SheetFeedbackItem object : feedbackItems())
        {
            deleteFeedbackItemsRelationship(object);
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entities pointed to by the <code>submissions</code>
     * relationship.
     * @return an NSArray of the entities in the relationship
     */
    @SuppressWarnings("unchecked")
    public NSArray<org.webcat.schedulesheets.ScheduleSheetSubmission> submissions()
    {
        return (NSArray)storedValueForKey( "submissions" );
    }


    // ----------------------------------------------------------
    /**
     * Replace the list of entities pointed to by the
     * <code>submissions</code> relationship.
     *
     * @param value The new set of entities to relate to
     */
    public void setSubmissions( NSMutableArray<org.webcat.schedulesheets.ScheduleSheetSubmission>  value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setSubmissions("
                + value + "): was " + submissions() );
        }
        takeStoredValueForKey( value, "submissions" );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>submissions</code>
     * relationship (DO NOT USE--instead, use
     * <code>addToSubmissionsRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void addToSubmissions( org.webcat.schedulesheets.ScheduleSheetSubmission value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToSubmissions("
                + value + "): was " + submissions() );
        }
        NSMutableArray<org.webcat.schedulesheets.ScheduleSheetSubmission> array =
            (NSMutableArray<org.webcat.schedulesheets.ScheduleSheetSubmission>)submissions();
        willChange();
        array.addObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>submissions</code>
     * relationship (DO NOT USE--instead, use
     * <code>removeFromSubmissionsRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromSubmissions( org.webcat.schedulesheets.ScheduleSheetSubmission value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "RemoveFromSubmissions("
                + value + "): was " + submissions() );
        }
        NSMutableArray<org.webcat.schedulesheets.ScheduleSheetSubmission> array =
            (NSMutableArray<org.webcat.schedulesheets.ScheduleSheetSubmission>)submissions();
        willChange();
        array.removeObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>submissions</code>
     * relationship.
     *
     * @param value The new entity to relate to
     */
    public void addToSubmissionsRelationship( org.webcat.schedulesheets.ScheduleSheetSubmission value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToSubmissionsRelationship("
                + value + "): was " + submissions() );
        }
        addObjectToBothSidesOfRelationshipWithKey(
            value, "submissions" );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>submissions</code>
     * relationship.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromSubmissionsRelationship( org.webcat.schedulesheets.ScheduleSheetSubmission value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "removeFromSubmissionsRelationship("
                + value + "): was " + submissions() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "submissions" );
    }


    // ----------------------------------------------------------
    /**
     * Create a brand new object that is a member of the
     * <code>submissions</code> relationship.
     *
     * @return The new entity
     */
    public org.webcat.schedulesheets.ScheduleSheetSubmission createSubmissionsRelationship()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "createSubmissionsRelationship()" );
        }
        EOClassDescription eoClassDesc = EOClassDescription
            .classDescriptionForEntityName( "ScheduleSheetSubmission" );
        EOEnterpriseObject eoObject = eoClassDesc
            .createInstanceWithEditingContext( editingContext(), null );
        editingContext().insertObject( eoObject );
        addObjectToBothSidesOfRelationshipWithKey(
            eoObject, "submissions" );
        return (org.webcat.schedulesheets.ScheduleSheetSubmission)eoObject;
    }


    // ----------------------------------------------------------
    /**
     * Remove and then delete a specific entity that is a member of the
     * <code>submissions</code> relationship.
     *
     * @param value The entity to remove from the relationship and then delete
     */
    public void deleteSubmissionsRelationship( org.webcat.schedulesheets.ScheduleSheetSubmission value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteSubmissionsRelationship("
                + value + "): was " + submissions() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "submissions" );
        editingContext().deleteObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove (and then delete, if owned) all entities that are members of the
     * <code>submissions</code> relationship.
     */
    public void deleteAllSubmissionsRelationships()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteAllSubmissionsRelationships(): was "
                + submissions() );
        }
        for (org.webcat.schedulesheets.ScheduleSheetSubmission object : submissions())
        {
            deleteSubmissionsRelationship(object);
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a fetch specification.
     *
     * @param context The editing context to use
     * @param fspec The fetch specification to use
     *
     * @return an NSArray of the entities retrieved
     */
    @SuppressWarnings("unchecked")
    public static NSArray<ScheduleSheet> objectsWithFetchSpecification(
        EOEditingContext context,
        EOFetchSpecification fspec)
    {
        return context.objectsWithFetchSpecification(fspec);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve all objects of this type.
     *
     * @param context The editing context to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<ScheduleSheet> allObjects(
        EOEditingContext context)
    {
        return objectsMatchingQualifier(context, null, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a qualifier.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<ScheduleSheet> objectsMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier)
    {
        return objectsMatchingQualifier(context, qualifier, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a qualifier and sort orderings.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     * @param sortOrderings The sort orderings to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<ScheduleSheet> objectsMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier,
        NSArray<EOSortOrdering> sortOrderings)
    {
        @SuppressWarnings("unchecked")
        EOFetchSpecification fspec = new WCFetchSpecification(
                ENTITY_NAME, qualifier, sortOrderings);
        fspec.setUsesDistinct(true);
        return objectsWithFetchSpecification(context, fspec);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the first object that matches a qualifier, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     * @param sortOrderings the sort orderings
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static ScheduleSheet firstObjectMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier,
        NSArray<EOSortOrdering> sortOrderings)
    {
        NSArray<ScheduleSheet> objects =
            objectsMatchingQualifier(context, qualifier, sortOrderings);
        return (objects.size() > 0)
            ? objects.get(0)
            : null;
    }


    // ----------------------------------------------------------
    /**
     * Retrieve a single object using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return the single entity that was retrieved
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static ScheduleSheet uniqueObjectMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier) throws EOUtilities.MoreThanOneException
    {
        NSArray<ScheduleSheet> objects =
            objectsMatchingQualifier(context, qualifier);
        if (objects.size() > 1)
        {
            String msg = "fetching ScheduleSheet";
            try
            {
                if (qualifier != null)
                {
                    msg += " where " + qualifier;
                }
                msg += ", result = " + objects;
            }
            catch (Exception e)
            {
                log.error("Exception building MoreThanOneException message, "
                    + "contents so far: " + msg, e);
            }
            throw new EOUtilities.MoreThanOneException(msg);
        }
        return (objects.size() > 0)
            ? objects.get(0)
            : null;
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<ScheduleSheet> objectsMatchingValues(
        EOEditingContext context,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value "
                + "corresponding to every key that was passed. Args = "
                + java.util.Arrays.toString(keysAndValues));
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (key == null)
            {
                throw new IllegalArgumentException(
                    "Found null where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }
            else if (!(key instanceof String))
            {
                throw new IllegalArgumentException(
                    "Found a " + key.getClass().getName() + " [" + key + "]"
                    + " where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }

            valueDictionary.setObjectForKey(value, key);
        }

        return objectsMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a dictionary of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return an NSArray of the entities retrieved
     */
    @SuppressWarnings("unchecked")
    public static NSArray<ScheduleSheet> objectsMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
    {
        return EOUtilities.objectsMatchingValues(context, ENTITY_NAME,
            keysAndValues);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the first object that matches a set of keys and values, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param sortOrderings the sort orderings
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static ScheduleSheet firstObjectMatchingValues(
        EOEditingContext context,
        NSArray<EOSortOrdering> sortOrderings,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value "
                + "corresponding to every key that was passed. Args = "
                + java.util.Arrays.toString(keysAndValues));
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (key == null)
            {
                throw new IllegalArgumentException(
                    "Found null where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }
            else if (!(key instanceof String))
            {
                throw new IllegalArgumentException(
                    "Found a " + key.getClass().getName() + " [" + key + "]"
                    + " where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }

            valueDictionary.setObjectForKey(value, key);
        }

        return firstObjectMatchingValues(
            context, sortOrderings, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieves the first object that matches a set of keys and values, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param sortOrderings the sort orderings
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static ScheduleSheet firstObjectMatchingValues(
        EOEditingContext context,
        NSArray<EOSortOrdering> sortOrderings,
        NSDictionary<String, Object> keysAndValues)
    {
        @SuppressWarnings("unchecked")
        EOFetchSpecification fspec = new WCFetchSpecification(
                ENTITY_NAME,
                EOQualifier.qualifierToMatchAllValues(keysAndValues),
                sortOrderings);
        fspec.setFetchLimit(1);

        NSArray<ScheduleSheet> objects =
            objectsWithFetchSpecification( context, fspec );

        if ( objects.count() == 0 )
        {
            return null;
        }
        else
        {
            return objects.objectAtIndex(0);
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve a single object using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the single entity that was retrieved, or null if there was none
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static ScheduleSheet uniqueObjectMatchingValues(
        EOEditingContext context,
        Object... keysAndValues) throws EOUtilities.MoreThanOneException
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value "
                + "corresponding to every key that was passed. Args = "
                + java.util.Arrays.toString(keysAndValues));
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (key == null)
            {
                throw new IllegalArgumentException(
                    "Found null where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }
            else if (!(key instanceof String))
            {
                throw new IllegalArgumentException(
                    "Found a " + key.getClass().getName() + " [" + key + "]"
                    + " where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }

            valueDictionary.setObjectForKey(value, key);
        }

        return uniqueObjectMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve an object using a dictionary of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the single entity that was retrieved, or null if there was none
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static ScheduleSheet uniqueObjectMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
        throws EOUtilities.MoreThanOneException
    {
        try
        {
            return (ScheduleSheet)EOUtilities.objectMatchingValues(
                context, ENTITY_NAME, keysAndValues);
        }
        catch (EOObjectNotAvailableException e)
        {
            return null;
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of all objects of this type.
     *
     * @param context The editing context to use
     *
     * @return the count of all objects
     */
    public static int countOfAllObjects(EOEditingContext context)
    {
        return countOfObjectsMatchingQualifier(context, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects that match a qualifier.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return the count of objects matching the qualifier
     */
    public static int countOfObjectsMatchingQualifier(
        EOEditingContext context, EOQualifier qualifier)
    {
        return ERXEOControlUtilities.objectCountWithQualifier(
                context, ENTITY_NAME, qualifier);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the count of objects that match the specified values
     */
    public static int countOfObjectsMatchingValues(
        EOEditingContext context,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value "
                + "corresponding to every key that was passed. Args = "
                + java.util.Arrays.toString(keysAndValues));
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (key == null)
            {
                throw new IllegalArgumentException(
                    "Found null where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }
            else if (!(key instanceof String))
            {
                throw new IllegalArgumentException(
                    "Found a " + key.getClass().getName() + " [" + key + "]"
                    + " where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }

            valueDictionary.setObjectForKey(value, key);
        }

        return countOfObjectsMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects using a dictionary of keys and values to
     * match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the count of objects that matched the specified values
     */
    public static int countOfObjectsMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
    {
        return countOfObjectsMatchingQualifier(context,
                EOQualifier.qualifierToMatchAllValues(keysAndValues));
    }


    // ----------------------------------------------------------
    /**
     * Produce a string representation of this object.  This implementation
     * calls UserPresentableDescription(), which uses WebObjects' internal
     * mechanism to print out the visible fields of this object.  Normally,
     * subclasses would override userPresentableDescription() to change
     * the way the object is printed.
     *
     * @return A string representation of the object's value
     */
    public String toString()
    {
        return userPresentableDescription();
    }


    //~ Instance/static variables .............................................

    static Logger log = Logger.getLogger(ScheduleSheet.class);
}
