/*==========================================================================*\
 |  _SheetFeedbackItem.java
 |*-------------------------------------------------------------------------*|
 |  Created by eogenerator
 |  DO NOT EDIT.  Make changes to SheetFeedbackItem.java instead.
 |*-------------------------------------------------------------------------*|
 |  Copyright (C) 2006-2012 Virginia Tech
 |
 |  This file is part of Web-CAT.
 |
 |  Web-CAT is free software; you can redistribute it and/or modify
 |  it under the terms of the GNU Affero General Public License as published
 |  by the Free Software Foundation; either version 3 of the License, or
 |  (at your option) any later version.
 |
 |  Web-CAT is distributed in the hope that it will be useful,
 |  but WITHOUT ANY WARRANTY; without even the implied warranty of
 |  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 |  GNU General Public License for more details.
 |
 |  You should have received a copy of the GNU Affero General Public License
 |  along with Web-CAT; if not, see <http://www.gnu.org/licenses/>.
\*==========================================================================*/

package org.webcat.schedulesheets;

import com.webobjects.eoaccess.*;
import com.webobjects.eocontrol.*;
import com.webobjects.foundation.*;
import er.extensions.eof.ERXEOControlUtilities;
import er.extensions.eof.ERXKey;
import org.apache.log4j.Logger;
import org.webcat.core.EOBasedKeyGenerator;
import org.webcat.woextensions.WCFetchSpecification;

// -------------------------------------------------------------------------
/**
 * An automatically generated EOGenericRecord subclass.  DO NOT EDIT.
 * To change, use EOModeler, or make additions in
 * SheetFeedbackItem.java.
 *
 * @author Generated by eogenerator
 * @version version suppressed to control auto-generation
 */
public abstract class _SheetFeedbackItem
    extends org.webcat.core.EOBase
{
    //~ Constructors ..........................................................

    // ----------------------------------------------------------
    /**
     * Creates a new _SheetFeedbackItem object.
     */
    public _SheetFeedbackItem()
    {
        super();
    }


    // ----------------------------------------------------------
    /**
     * A static factory method for creating a new
     * SheetFeedbackItem object given required
     * attributes and relationships.
     * @param editingContext The context in which the new object will be
     * inserted
     * @param categoryValue
     * @param checkRoundValue
     * @param codeValue
     * @return The newly created object
     */
    public static SheetFeedbackItem create(
        EOEditingContext editingContext,
        Integer categoryValue,
        int checkRoundValue,
        int codeValue
        )
    {
        SheetFeedbackItem eoObject = (SheetFeedbackItem)
            EOUtilities.createAndInsertInstance(
                editingContext,
                _SheetFeedbackItem.ENTITY_NAME);
        eoObject.setCategory(categoryValue);
        eoObject.setCheckRound(checkRoundValue);
        eoObject.setCode(codeValue);
        return eoObject;
    }


    // ----------------------------------------------------------
    /**
     * Get a local instance of the given object in another editing context.
     * @param editingContext The target editing context
     * @param eo The object to import
     * @return An instance of the given object in the target editing context
     */
    public static SheetFeedbackItem localInstance(
        EOEditingContext editingContext, SheetFeedbackItem eo)
    {
        return (eo == null)
            ? null
            : (SheetFeedbackItem)EOUtilities.localInstanceOfObject(
                editingContext, eo);
    }


    // ----------------------------------------------------------
    /**
     * Look up an object by id number.  Assumes the editing
     * context is appropriately locked.
     * @param ec The editing context to use
     * @param id The id to look up
     * @return The object, or null if no such id exists
     */
    public static SheetFeedbackItem forId(
        EOEditingContext ec, int id)
    {
        SheetFeedbackItem obj = null;
        if (id > 0)
        {
            NSArray<SheetFeedbackItem> objects =
                objectsMatchingValues(ec, "id", new Integer(id));
            if (objects != null && objects.count() > 0)
            {
                obj = objects.objectAtIndex(0);
            }
        }
        return obj;
    }


    // ----------------------------------------------------------
    /**
     * Look up an object by id number.  Assumes the editing
     * context is appropriately locked.
     * @param ec The editing context to use
     * @param id The id to look up
     * @return The object, or null if no such id exists
     */
    public static SheetFeedbackItem forId(
        EOEditingContext ec, String id)
    {
        return forId(ec, er.extensions.foundation.ERXValueUtilities.intValue(id));
    }


    //~ Constants (for key names) .............................................

    // Attributes ---
    public static final String CATEGORY_KEY = "category";
    public static final ERXKey<Integer> category =
        new ERXKey<Integer>(CATEGORY_KEY);
    public static final String CHECK_ROUND_KEY = "checkRound";
    public static final ERXKey<Integer> checkRound =
        new ERXKey<Integer>(CHECK_ROUND_KEY);
    public static final String CODE_KEY = "code";
    public static final ERXKey<Integer> code =
        new ERXKey<Integer>(CODE_KEY);
    public static final String MESSAGE_KEY = "message";
    public static final ERXKey<String> message =
        new ERXKey<String>(MESSAGE_KEY);
    // To-one relationships ---
    public static final String COMPONENT_FEATURE_KEY = "componentFeature";
    public static final ERXKey<org.webcat.schedulesheets.ComponentFeature> componentFeature =
        new ERXKey<org.webcat.schedulesheets.ComponentFeature>(COMPONENT_FEATURE_KEY);
    public static final String SHEET_KEY = "sheet";
    public static final ERXKey<org.webcat.schedulesheets.ScheduleSheet> sheet =
        new ERXKey<org.webcat.schedulesheets.ScheduleSheet>(SHEET_KEY);
    public static final String SHEET_ENTRY_KEY = "sheetEntry";
    public static final ERXKey<org.webcat.schedulesheets.SheetEntry> sheetEntry =
        new ERXKey<org.webcat.schedulesheets.SheetEntry>(SHEET_ENTRY_KEY);
    // To-many relationships ---
    // Fetch specifications ---
    public static final String ENTITY_NAME = "SheetFeedbackItem";

    public transient final EOBasedKeyGenerator generateKey =
        new EOBasedKeyGenerator(this);


    //~ Methods ...............................................................

    // ----------------------------------------------------------
    /**
     * Get a local instance of this object in another editing context.
     * @param editingContext The target editing context
     * @return An instance of this object in the target editing context
     */
    public SheetFeedbackItem localInstance(EOEditingContext editingContext)
    {
        return (SheetFeedbackItem)EOUtilities.localInstanceOfObject(
            editingContext, this);
    }


    // ----------------------------------------------------------
    /**
     * Get a list of changes between this object's current state and the
     * last committed version.
     * @return a dictionary of the changes that have not yet been committed
     */
    @SuppressWarnings("unchecked")
    public NSDictionary<String, Object> changedProperties()
    {
        return changesFromSnapshot(
            editingContext().committedSnapshotForObject(this));
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>id</code> value.
     * @return the value of the attribute
     */
    public Number id()
    {
        try
        {
            return (Number)EOUtilities.primaryKeyForObject(
                editingContext() , this).objectForKey("id");
        }
        catch (Exception e)
        {
            return er.extensions.eof.ERXConstant.ZeroInteger;
        }
    }

    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>category</code> value.
     * @return the value of the attribute
     */
    public Integer category()
    {
        return (Integer)storedValueForKey( "category" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>category</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setCategory( Integer value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setCategory("
                + value + "): was " + category() );
        }
        takeStoredValueForKey( value, "category" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>checkRound</code> value.
     * @return the value of the attribute
     */
    public int checkRound()
    {
        Integer returnValue =
            (Integer)storedValueForKey( "checkRound" );
        return ( returnValue == null )
            ? 0
            : returnValue.intValue();
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>checkRound</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setCheckRound( int value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setCheckRound("
                + value + "): was " + checkRound() );
        }
        Integer actual =
            er.extensions.eof.ERXConstant.integerForInt( value );
            setCheckRoundRaw( actual );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>checkRound</code> value.
     * @return the value of the attribute
     */
    public Integer checkRoundRaw()
    {
        return (Integer)storedValueForKey( "checkRound" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>checkRound</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setCheckRoundRaw( Integer value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setCheckRoundRaw("
                + value + "): was " + checkRoundRaw() );
        }
        takeStoredValueForKey( value, "checkRound" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>code</code> value.
     * @return the value of the attribute
     */
    public int code()
    {
        Integer returnValue =
            (Integer)storedValueForKey( "code" );
        return ( returnValue == null )
            ? 0
            : returnValue.intValue();
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>code</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setCode( int value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setCode("
                + value + "): was " + code() );
        }
        Integer actual =
            er.extensions.eof.ERXConstant.integerForInt( value );
            setCodeRaw( actual );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>code</code> value.
     * @return the value of the attribute
     */
    public Integer codeRaw()
    {
        return (Integer)storedValueForKey( "code" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>code</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setCodeRaw( Integer value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setCodeRaw("
                + value + "): was " + codeRaw() );
        }
        takeStoredValueForKey( value, "code" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>message</code> value.
     * @return the value of the attribute
     */
    public String message()
    {
        return (String)storedValueForKey( "message" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>message</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setMessage( String value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setMessage("
                + value + "): was " + message() );
        }
        takeStoredValueForKey( value, "message" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entity pointed to by the <code>componentFeature</code>
     * relationship.
     * @return the entity in the relationship
     */
    public org.webcat.schedulesheets.ComponentFeature componentFeature()
    {
        return (org.webcat.schedulesheets.ComponentFeature)storedValueForKey( "componentFeature" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>componentFeature</code>
     * relationship (DO NOT USE--instead, use
     * <code>setComponentFeatureRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void setComponentFeature( org.webcat.schedulesheets.ComponentFeature value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setComponentFeature("
                + value + "): was " + componentFeature() );
        }
        takeStoredValueForKey( value, "componentFeature" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>componentFeature</code>
     * relationship.  This method is a type-safe version of
     * <code>addObjectToBothSidesOfRelationshipWithKey()</code>.
     *
     * @param value The new entity to relate to
     */
    public void setComponentFeatureRelationship(
        org.webcat.schedulesheets.ComponentFeature value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setComponentFeatureRelationship("
                + value + "): was " + componentFeature() );
        }
        if ( value == null )
        {
            org.webcat.schedulesheets.ComponentFeature object = componentFeature();
            if ( object != null )
                removeObjectFromBothSidesOfRelationshipWithKey( object, "componentFeature" );
        }
        else
        {
            addObjectToBothSidesOfRelationshipWithKey( value, "componentFeature" );
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entity pointed to by the <code>sheet</code>
     * relationship.
     * @return the entity in the relationship
     */
    public org.webcat.schedulesheets.ScheduleSheet sheet()
    {
        return (org.webcat.schedulesheets.ScheduleSheet)storedValueForKey( "sheet" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>sheet</code>
     * relationship (DO NOT USE--instead, use
     * <code>setSheetRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void setSheet( org.webcat.schedulesheets.ScheduleSheet value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setSheet("
                + value + "): was " + sheet() );
        }
        takeStoredValueForKey( value, "sheet" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>sheet</code>
     * relationship.  This method is a type-safe version of
     * <code>addObjectToBothSidesOfRelationshipWithKey()</code>.
     *
     * @param value The new entity to relate to
     */
    public void setSheetRelationship(
        org.webcat.schedulesheets.ScheduleSheet value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setSheetRelationship("
                + value + "): was " + sheet() );
        }
        if ( value == null )
        {
            org.webcat.schedulesheets.ScheduleSheet object = sheet();
            if ( object != null )
                removeObjectFromBothSidesOfRelationshipWithKey( object, "sheet" );
        }
        else
        {
            addObjectToBothSidesOfRelationshipWithKey( value, "sheet" );
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entity pointed to by the <code>sheetEntry</code>
     * relationship.
     * @return the entity in the relationship
     */
    public org.webcat.schedulesheets.SheetEntry sheetEntry()
    {
        return (org.webcat.schedulesheets.SheetEntry)storedValueForKey( "sheetEntry" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>sheetEntry</code>
     * relationship (DO NOT USE--instead, use
     * <code>setSheetEntryRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void setSheetEntry( org.webcat.schedulesheets.SheetEntry value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setSheetEntry("
                + value + "): was " + sheetEntry() );
        }
        takeStoredValueForKey( value, "sheetEntry" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>sheetEntry</code>
     * relationship.  This method is a type-safe version of
     * <code>addObjectToBothSidesOfRelationshipWithKey()</code>.
     *
     * @param value The new entity to relate to
     */
    public void setSheetEntryRelationship(
        org.webcat.schedulesheets.SheetEntry value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setSheetEntryRelationship("
                + value + "): was " + sheetEntry() );
        }
        if ( value == null )
        {
            org.webcat.schedulesheets.SheetEntry object = sheetEntry();
            if ( object != null )
                removeObjectFromBothSidesOfRelationshipWithKey( object, "sheetEntry" );
        }
        else
        {
            addObjectToBothSidesOfRelationshipWithKey( value, "sheetEntry" );
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a fetch specification.
     *
     * @param context The editing context to use
     * @param fspec The fetch specification to use
     *
     * @return an NSArray of the entities retrieved
     */
    @SuppressWarnings("unchecked")
    public static NSArray<SheetFeedbackItem> objectsWithFetchSpecification(
        EOEditingContext context,
        EOFetchSpecification fspec)
    {
        return context.objectsWithFetchSpecification(fspec);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve all objects of this type.
     *
     * @param context The editing context to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<SheetFeedbackItem> allObjects(
        EOEditingContext context)
    {
        return objectsMatchingQualifier(context, null, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a qualifier.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<SheetFeedbackItem> objectsMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier)
    {
        return objectsMatchingQualifier(context, qualifier, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a qualifier and sort orderings.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     * @param sortOrderings The sort orderings to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<SheetFeedbackItem> objectsMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier,
        NSArray<EOSortOrdering> sortOrderings)
    {
        WCFetchSpecification<SheetFeedbackItem> fspec =
            new WCFetchSpecification<SheetFeedbackItem>(
                ENTITY_NAME, qualifier, sortOrderings);
        fspec.setUsesDistinct(true);
        return objectsWithFetchSpecification(context, fspec);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the first object that matches a qualifier, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     * @param sortOrderings the sort orderings
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static SheetFeedbackItem firstObjectMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier,
        NSArray<EOSortOrdering> sortOrderings)
    {
        WCFetchSpecification<SheetFeedbackItem> fspec =
            new WCFetchSpecification<SheetFeedbackItem>(
                ENTITY_NAME, qualifier, sortOrderings);
        fspec.setUsesDistinct(true);
        fspec.setFetchLimit(1);
        NSArray<SheetFeedbackItem> objects =
            objectsWithFetchSpecification(context, fspec);
        return (objects.size() > 0)
            ? objects.get(0)
            : null;
    }


    // ----------------------------------------------------------
    /**
     * Retrieve a single object using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return the single entity that was retrieved
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static SheetFeedbackItem uniqueObjectMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier) throws EOUtilities.MoreThanOneException
    {
        NSArray<SheetFeedbackItem> objects =
            objectsMatchingQualifier(context, qualifier);
        if (objects.size() > 1)
        {
            String msg = "fetching SheetFeedbackItem";
            try
            {
                if (qualifier != null)
                {
                    msg += " where " + qualifier;
                }
                msg += ", result = " + objects;
            }
            catch (Exception e)
            {
                log.error("Exception building MoreThanOneException message, "
                    + "contents so far: " + msg, e);
            }
            throw new EOUtilities.MoreThanOneException(msg);
        }
        return (objects.size() > 0)
            ? objects.get(0)
            : null;
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<SheetFeedbackItem> objectsMatchingValues(
        EOEditingContext context,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value "
                + "corresponding to every key that was passed. Args = "
                + java.util.Arrays.toString(keysAndValues));
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (key == null)
            {
                throw new IllegalArgumentException(
                    "Found null where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }
            else if (!(key instanceof String))
            {
                throw new IllegalArgumentException(
                    "Found a " + key.getClass().getName() + " [" + key + "]"
                    + " where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }

            valueDictionary.setObjectForKey(value, (String)key);
        }

        return objectsMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a dictionary of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return an NSArray of the entities retrieved
     */
    @SuppressWarnings("unchecked")
    public static NSArray<SheetFeedbackItem> objectsMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
    {
        return EOUtilities.objectsMatchingValues(context, ENTITY_NAME,
            keysAndValues);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the first object that matches a set of keys and values, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param sortOrderings the sort orderings
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static SheetFeedbackItem firstObjectMatchingValues(
        EOEditingContext context,
        NSArray<EOSortOrdering> sortOrderings,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value "
                + "corresponding to every key that was passed. Args = "
                + java.util.Arrays.toString(keysAndValues));
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (key == null)
            {
                throw new IllegalArgumentException(
                    "Found null where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }
            else if (!(key instanceof String))
            {
                throw new IllegalArgumentException(
                    "Found a " + key.getClass().getName() + " [" + key + "]"
                    + " where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }

            valueDictionary.setObjectForKey(value, key);
        }

        return firstObjectMatchingValues(
            context, sortOrderings, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieves the first object that matches a set of keys and values, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param sortOrderings the sort orderings
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static SheetFeedbackItem firstObjectMatchingValues(
        EOEditingContext context,
        NSArray<EOSortOrdering> sortOrderings,
        NSDictionary<String, Object> keysAndValues)
    {
        WCFetchSpecification<SheetFeedbackItem> fspec =
            new WCFetchSpecification<SheetFeedbackItem>(
                ENTITY_NAME,
                EOQualifier.qualifierToMatchAllValues(keysAndValues),
                sortOrderings);
        fspec.setFetchLimit(1);

        NSArray<SheetFeedbackItem> objects =
            objectsWithFetchSpecification( context, fspec );

        if ( objects.count() == 0 )
        {
            return null;
        }
        else
        {
            return objects.objectAtIndex(0);
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve a single object using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the single entity that was retrieved, or null if there was none
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static SheetFeedbackItem uniqueObjectMatchingValues(
        EOEditingContext context,
        Object... keysAndValues) throws EOUtilities.MoreThanOneException
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value "
                + "corresponding to every key that was passed. Args = "
                + java.util.Arrays.toString(keysAndValues));
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (key == null)
            {
                throw new IllegalArgumentException(
                    "Found null where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }
            else if (!(key instanceof String))
            {
                throw new IllegalArgumentException(
                    "Found a " + key.getClass().getName() + " [" + key + "]"
                    + " where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }

            valueDictionary.setObjectForKey(value, key);
        }

        return uniqueObjectMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve an object using a dictionary of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the single entity that was retrieved, or null if there was none
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static SheetFeedbackItem uniqueObjectMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
        throws EOUtilities.MoreThanOneException
    {
        try
        {
            return (SheetFeedbackItem)EOUtilities.objectMatchingValues(
                context, ENTITY_NAME, keysAndValues);
        }
        catch (EOObjectNotAvailableException e)
        {
            return null;
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of all objects of this type.
     *
     * @param context The editing context to use
     *
     * @return the count of all objects
     */
    public static int countOfAllObjects(EOEditingContext context)
    {
        return countOfObjectsMatchingQualifier(context, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects that match a qualifier.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return the count of objects matching the qualifier
     */
    public static int countOfObjectsMatchingQualifier(
        EOEditingContext context, EOQualifier qualifier)
    {
        return ERXEOControlUtilities.objectCountWithQualifier(
                context, ENTITY_NAME, qualifier);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the count of objects that match the specified values
     */
    public static int countOfObjectsMatchingValues(
        EOEditingContext context,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value "
                + "corresponding to every key that was passed. Args = "
                + java.util.Arrays.toString(keysAndValues));
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (key == null)
            {
                throw new IllegalArgumentException(
                    "Found null where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }
            else if (!(key instanceof String))
            {
                throw new IllegalArgumentException(
                    "Found a " + key.getClass().getName() + " [" + key + "]"
                    + " where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }

            valueDictionary.setObjectForKey(value, key);
        }

        return countOfObjectsMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects using a dictionary of keys and values to
     * match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the count of objects that matched the specified values
     */
    public static int countOfObjectsMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
    {
        return countOfObjectsMatchingQualifier(context,
                EOQualifier.qualifierToMatchAllValues(keysAndValues));
    }


    // ----------------------------------------------------------
    /**
     * Produce a string representation of this object.  This implementation
     * calls UserPresentableDescription(), which uses WebObjects' internal
     * mechanism to print out the visible fields of this object.  Normally,
     * subclasses would override userPresentableDescription() to change
     * the way the object is printed.
     *
     * @return A string representation of the object's value
     */
    public String toString()
    {
        return userPresentableDescription();
    }


    //~ Instance/static variables .............................................

    static Logger log = Logger.getLogger(SheetFeedbackItem.class);
}
